// ═══════════════════════════════════════════════════════════════
//  ПРОФОРИЕНТАЦИЯ — Domain Discovery Quiz
//  10 questions → 6 domains → recommend a field of study
//  Supported languages: ru, en, de, fr, es, pt, ar, he
// ═══════════════════════════════════════════════════════════════

// Language-independent scoring matrix
// Each question has 6 options, each option maps domain keys → score
const PO_QS = [
  // Q1 — What fascinates you most?
  { opts:[
    {s:{it:3}},
    {s:{creative:3}},
    {s:{business:3}},
    {s:{science:3}},
    {s:{social:3}},
    {s:{engineering:3}}
  ]},
  // Q2 — Favourite school subject?
  { opts:[
    {s:{it:3,engineering:1}},
    {s:{creative:3}},
    {s:{business:3}},
    {s:{science:3}},
    {s:{social:2,creative:1}},
    {s:{engineering:3,it:1}}
  ]},
  // Q3 — Free time activity?
  { opts:[
    {s:{it:3}},
    {s:{creative:3}},
    {s:{business:2,creative:1}},
    {s:{science:3}},
    {s:{social:3}},
    {s:{engineering:3}}
  ]},
  // Q4 — How do you solve problems?
  { opts:[
    {s:{it:3}},
    {s:{creative:3}},
    {s:{business:3}},
    {s:{science:3}},
    {s:{social:3}},
    {s:{engineering:3}}
  ]},
  // Q5 — Free project — what do you choose?
  { opts:[
    {s:{it:3}},
    {s:{creative:3}},
    {s:{business:3}},
    {s:{science:3}},
    {s:{social:3}},
    {s:{engineering:3}}
  ]},
  // Q6 — What matters most at work?
  { opts:[
    {s:{it:2,engineering:1}},
    {s:{creative:3}},
    {s:{business:3}},
    {s:{science:3}},
    {s:{social:3}},
    {s:{engineering:3}}
  ]},
  // Q7 — Imagine yourself in 10 years
  { opts:[
    {s:{it:3}},
    {s:{creative:3}},
    {s:{business:3}},
    {s:{science:3}},
    {s:{social:3}},
    {s:{engineering:3}}
  ]},
  // Q8 — How do you prefer to work?
  { opts:[
    {s:{it:3}},
    {s:{creative:3}},
    {s:{business:3}},
    {s:{science:3}},
    {s:{social:3}},
    {s:{engineering:3}}
  ]},
  // Q9 — What comes naturally to you?
  { opts:[
    {s:{it:3}},
    {s:{creative:3}},
    {s:{business:3}},
    {s:{science:3,it:1}},
    {s:{social:3}},
    {s:{engineering:3}}
  ]},
  // Q10 — If money didn't matter, what would you do?
  { opts:[
    {s:{it:3}},
    {s:{creative:3}},
    {s:{business:3}},
    {s:{science:3}},
    {s:{social:3}},
    {s:{engineering:3}}
  ]}
];

// Domain metadata (language-independent parts)
const PO_DOMAINS = {
  it:          { icon:'💻', available: true  },
  creative:    { icon:'🎨', available: true  },
  business:    { icon:'💼', available: true  },
  science:     { icon:'🔬', available: true  },
  social:      { icon:'👥', available: true  },
  engineering: { icon:'🔧', available: true  }
};

// All UI strings and question text per language
const PO_I18N = {

  // ──────────────────────────────────────────── РУССКИЙ ──
  ru: {
    tag:   'Профориентация',
    title: 'Какая область тебе подходит?',
    sub:   '10 вопросов — узнай своё направление',
    back:  '← На главную',
    prog:  (n,t) => `Вопрос ${n} из ${t}`,
    resTag:'Твоё направление',
    resSub:'На основе твоих ответов',
    goTest:'Пройти тест IT-профессий →', goTestCreative:'Пройти тест творческих профессий →', goTestBusiness:'Пройти тест бизнес-профессий →', goTestScience:'Пройти тест науки и медицины →', goTestSocial:'Пройти тест педагогики и общества →', goTestEngineering:'Пройти тест инженерии и производства →',
    soon:  'Тест для этого направления скоро появится!',
    testSoon:'Тест — скоро',
    alsoIt:'Пока также рекомендуем: тест IT-профессий',
    restart:'← Пройти ещё раз',
    multiHint:'можно выбрать несколько',
    domains:{
      it:          'IT и технологии',
      creative:    'Творчество и медиа',
      business:    'Бизнес и маркетинг',
      science:     'Наука и медицина',
      social:      'Педагогика и общество',
      engineering: 'Инженерия и производство'
    },
    domainDesc:{
      it:          'Программирование, данные, кибербезопасность, DevOps',
      creative:    'Дизайн, видео, иллюстрация, анимация',
      business:    'Маркетинг, продажи, предпринимательство, менеджмент',
      science:     'Медицина, биология, химия, физика, исследования',
      social:      'Преподавание, психология, HR, социальная работа',
      engineering: 'Механика, строительство, электроника, робототехника'
    },
    domainFull:{
      it:{
        who:'Тем, кто мыслит логически, любит решать задачи и строить системы. Идеально, если тебе интересны компьютеры, математика или алгоритмы.',
        profs:'Разработчик (frontend / backend), Data Scientist, DevOps-инженер, QA-тестировщик, Продакт-менеджер, Специалист по кибербезопасности, UX/UI-дизайнер',
        start:'Начни с Python или JavaScript — первые результаты видны уже через 1–2 месяца. Попробуй: python.org, javascript.info, freecodecamp.org'
      },
      creative:{
        who:'Тем, кто думает образами, чувствует красоту и хочет создавать то, что люди видят, слышат и чувствуют. Подходит интровертам и экстравертам.',
        profs:'Графический дизайнер, Видеограф, Иллюстратор, Аниматор, Фотограф, Моушн-дизайнер, Контент-мейкер, Арт-директор',
        start:'Начни с Figma (бесплатно) или попробуй нарисовать 30 иллюстраций за 30 дней. Смотри: figma.com, youtube-уроки по Adobe'
      },
      business:{
        who:'Тем, кто умеет убеждать, видит возможности там, где другие не замечают, и любит работать с людьми и результатом.',
        profs:'Маркетолог, SMM-специалист, Предприниматель, Таргетолог, Менеджер проекта, Бренд-менеджер, Копирайтер, Аналитик рекламы',
        start:'Попробуй продвинуть что-то в соцсетях или изучи основы маркетинга. Книга: «Заразительный» — Йона Бергер. Курсы: Coursera, Яндекс Практикум'
      },
      science:{
        who:'Тем, кто любит докапываться до сути, проводить эксперименты и понимать, как устроен мир — от клетки до вселенной.',
        profs:'Врач, Учёный-исследователь, Биотехнолог, Фармацевт, Химик, Физик, Эпидемиолог, Биоинформатик',
        start:'Углуби биологию или химию в школе. Читай научпоп: «Краткая история почти всего» — Билл Брайсон. Платформа: Khan Academy'
      },
      social:{
        who:'Тем, кто умеет слушать, понимает людей, хочет помогать и менять чьи-то жизни к лучшему.',
        profs:'Учитель, Психолог, Социальный педагог, HR-специалист, Карьерный консультант, Тренер, Логопед, Соцработник',
        start:'Начни с волонтёрства или помощи младшим. Книга: «Эмоциональный интеллект» — Дэниел Гоулман. Сайт: psyjourney.ru'
      },
      engineering:{
        who:'Тем, кто любит работать с конкретными вещами, видеть реальный результат и разбираться в том, как всё устроено физически.',
        profs:'Инженер-конструктор, Механик, Архитектор, Электрик, Строитель, Робототехник, Инженер по автоматизации, 3D-проектировщик',
        start:'Попробуй Arduino или 3D-печать. Смотри YouTube-каналы про инженерию. Книга: «Как всё устроено» — Маршалл Брейн'
      }
    },
    qs:[
      { q:'Что тебя больше всего увлекает?',
        h:'Выбери самое близкое',
        opts:['Создавать что-то в компьютере — игры, сайты, приложения',
              'Рисовать, снимать видео, создавать что-то красивое',
              'Организовывать людей, управлять, зарабатывать деньги',
              'Изучать природу, ставить опыты, лечить',
              'Общаться с людьми, помогать им, обучать',
              'Строить, чинить технику, работать руками']},
      { q:'Какой предмет тебе нравится больше всего?',
        h:'Один вариант',
        opts:['Информатика или математика',
              'Рисование, музыка или литература',
              'Обществознание или экономика',
              'Биология или химия',
              'История, русский язык или психология',
              'Физика или технология (труд)']},
      { q:'Что ты делаешь в свободное время?',
        h:'Честно — что чаще всего?',
        opts:['Программирую, делаю игры или изучаю технологии',
              'Рисую, снимаю видео, создаю контент',
              'Веду блог для заработка или ищу, как зарабатывать',
              'Читаю научное, провожу эксперименты, изучаю природу',
              'Занимаюсь с детьми, волонтёрю, помогаю другим',
              'Собираю, разбираю, ремонтирую технику']},
      { q:'Как ты лучше всего решаешь задачи?',
        h:'Твой стиль мышления',
        opts:['Через логику, алгоритмы и структуру',
              'Через образы, идеи и нестандартные решения',
              'Через переговоры, убеждение и управление людьми',
              'Через эксперименты, данные и анализ',
              'Через общение и понимание эмоций людей',
              'Через практику, инструменты и физические действия']},
      { q:'Тебе дали свободный проект. Что выбираешь?',
        h:'Первое, что приходит в голову',
        opts:['Написать программу или создать сайт',
              'Снять видеоролик или нарисовать иллюстрации',
              'Запустить маленький бизнес или рекламную кампанию',
              'Провести научный эксперимент',
              'Организовать помощь тем, кто в ней нуждается',
              'Сконструировать устройство или механизм']},
      { q:'Что важнее всего для тебя в будущей работе?',
        h:'Выбери главное',
        opts:['Работать с технологиями и решать сложные задачи',
              'Самовыражение и творческая свобода',
              'Карьерный рост и хороший заработок',
              'Делать открытия и понимать мир глубже',
              'Помогать людям и видеть свой вклад',
              'Видеть реальный физический результат своего труда']},
      { q:'Кем ты мог бы себя представить через 10 лет?',
        h:'Самая честная картинка',
        opts:['Программист, аналитик данных или специалист по кибербезопасности',
              'Дизайнер, видеограф, иллюстратор или аниматор',
              'Маркетолог, предприниматель или менеджер',
              'Врач, учёный, фармацевт или биотехнолог',
              'Учитель, психолог, HR или социальный работник',
              'Инженер, строитель, механик или архитектор']},
      { q:'Как тебе удобнее всего работать?',
        h:'Идеальная обстановка',
        opts:['За компьютером, с кодом и данными',
              'Создавая визуальные или звуковые образы',
              'Управляя людьми и процессами',
              'В лаборатории или с исследовательскими материалами',
              'Общаясь с людьми лично, в команде',
              'С оборудованием, инструментами или на производстве']},
      { q:'Что тебе даётся лучше всего?',
        h:'Твоя суперсила',
        opts:['Разбираться в технических системах',
              'Создавать красивые и оригинальные вещи',
              'Убеждать других и договариваться',
              'Систематизировать информацию и анализировать',
              'Слушать людей и понимать их потребности',
              'Работать руками и разбираться в механизмах']},
      { q:'Если бы деньги не имели значения — чем бы ты занимался?',
        h:'Честный ответ о своих ценностях',
        opts:['Писал бы код, создавал технологии или игры',
              'Занимался бы творчеством: рисовал, снимал, создавал',
              'Строил бы бизнес или инвестировал',
              'Изучал бы науку, проводил исследования',
              'Преподавал, помогал, работал с людьми',
              'Строил, изобретал, конструировал']}
    ]
  },

  // ──────────────────────────────────────────── ENGLISH ──
  en: {
    tag:   'Career Orientation',
    title: 'Which field suits you?',
    sub:   '10 questions — discover your direction',
    back:  '← Home',
    prog:  (n,t) => `Question ${n} of ${t}`,
    resTag:'Your direction',
    resSub:'Based on your answers',
    goTest:'Take the IT careers test →', goTestCreative:'Take the creative careers test →', goTestBusiness:'Take the business careers test →', goTestScience:'Take the science & medicine test →', goTestSocial:'Take the education & society test →', goTestEngineering:'Take the engineering & production test →',
    soon:  'A test for this field is coming soon!',
    testSoon:'Test — coming soon',
    alsoIt:'Meanwhile we recommend: IT careers test',
    restart:'← Take again',
    multiHint:'you can select multiple',
    domains:{
      it:          'IT & Technology',
      creative:    'Creative & Media',
      business:    'Business & Marketing',
      science:     'Science & Medicine',
      social:      'Education & Social',
      engineering: 'Engineering & Production'
    },
    domainDesc:{
      it:          'Programming, data, cybersecurity, DevOps',
      creative:    'Design, video, illustration, animation',
      business:    'Marketing, sales, entrepreneurship, management',
      science:     'Medicine, biology, chemistry, physics, research',
      social:      'Teaching, psychology, HR, social work',
      engineering: 'Mechanics, construction, electronics, robotics'
    },
    domainFull:{
      it:{
        who:'For those who think logically, love solving puzzles and building systems. Great fit if you\'re into computers, math or algorithms.',
        profs:'Developer (frontend / backend), Data Scientist, DevOps Engineer, QA Tester, Product Manager, Cybersecurity Specialist, UX/UI Designer',
        start:'Start with Python or JavaScript — you\'ll see real results within 1–2 months. Try: python.org, javascript.info, freecodecamp.org'
      },
      creative:{
        who:'For those who think in images, feel beauty and want to create things people see, hear and feel. Works for both introverts and extroverts.',
        profs:'Graphic Designer, Videographer, Illustrator, Animator, Photographer, Motion Designer, Content Creator, Art Director',
        start:'Start with Figma (free) or try drawing 30 illustrations in 30 days. See: figma.com, Adobe tutorials on YouTube'
      },
      business:{
        who:'For those who can persuade, spot opportunities others miss, and love working with people and results.',
        profs:'Marketer, SMM Specialist, Entrepreneur, Ads Specialist, Project Manager, Brand Manager, Copywriter, Advertising Analyst',
        start:'Try promoting something on social media or learn marketing basics. Book: "Contagious" by Jonah Berger. Courses: Coursera, HubSpot Academy'
      },
      science:{
        who:'For the curious who love digging into fundamentals, running experiments and understanding how the world works — from cells to galaxies.',
        profs:'Doctor, Research Scientist, Biotechnologist, Pharmacist, Chemist, Physicist, Epidemiologist, Bioinformatician',
        start:'Deepen biology or chemistry at school. Read popular science: "A Short History of Nearly Everything" by Bill Bryson. Platform: Khan Academy'
      },
      social:{
        who:'For empathetic people who listen well, understand others and want to help make someone\'s life better.',
        profs:'Teacher, Psychologist, Social Worker, HR Specialist, Career Counsellor, Coach, Speech Therapist',
        start:'Start with volunteering or helping someone learn a new skill. Book: "Emotional Intelligence" by Daniel Goleman. Site: coursera.org/social-science'
      },
      engineering:{
        who:'For those who love working with physical things, seeing tangible results and understanding how mechanisms work.',
        profs:'Design Engineer, Mechanic, Architect, Electrician, Construction Professional, Robotics Engineer, Automation Engineer, 3D Modeller',
        start:'Try Arduino or 3D printing. Watch engineering YouTube channels. Book: "How Everything Works" by Marshall Brain'
      }
    },
    qs:[
      { q:'What fascinates you the most?',
        h:'Pick the closest answer',
        opts:['Creating things on a computer — games, websites, apps',
              'Drawing, filming, making something beautiful',
              'Organising people, managing, making money',
              'Studying nature, doing experiments, healing',
              'Communicating with people, helping, teaching',
              'Building, fixing things, working with your hands']},
      { q:'Which school subject do you enjoy most?',
        h:'One answer',
        opts:['Computer science or maths',
              'Art, music or literature',
              'Social studies or economics',
              'Biology or chemistry',
              'History, languages or psychology',
              'Physics or technology / workshop']},
      { q:'What do you do in your free time?',
        h:'Be honest — what do you do most often?',
        opts:['Code, make games or explore new tech',
              'Draw, film videos, create content',
              'Run a blog for income or look for ways to earn',
              'Read science, experiment, explore nature',
              'Work with kids, volunteer, help others',
              'Assemble, disassemble or fix gadgets']},
      { q:'How do you best solve problems?',
        h:'Your thinking style',
        opts:['Through logic, algorithms and structure',
              'Through images, ideas and creative solutions',
              'Through negotiation, persuasion and people management',
              'Through experiments, data and analysis',
              'Through communication and understanding emotions',
              'Through practice, tools and physical actions']},
      { q:'You get a free project. What do you choose?',
        h:'First thing that comes to mind',
        opts:['Write a program or build a website',
              'Shoot a video or draw a series of illustrations',
              'Launch a small business or ad campaign',
              'Run a science experiment',
              'Organise help for those in need',
              'Design a device or mechanism']},
      { q:'What matters most to you in a future job?',
        h:'Pick the top priority',
        opts:['Working with technology and solving complex problems',
              'Self-expression and creative freedom',
              'Career growth and good earnings',
              'Making discoveries and understanding the world',
              'Helping people and seeing your impact',
              'Seeing the real physical result of your work']},
      { q:'Where do you picture yourself in 10 years?',
        h:'Most honest picture',
        opts:['Developer, data analyst or cybersecurity specialist',
              'Designer, videographer, illustrator or animator',
              'Marketer, entrepreneur or manager',
              'Doctor, scientist, pharmacist or biotech specialist',
              'Teacher, psychologist, HR or social worker',
              'Engineer, construction professional, mechanic or architect']},
      { q:'How do you prefer to work?',
        h:'Ideal environment',
        opts:['At a computer, with code and data',
              'Creating visual or audio content',
              'Managing people and processes',
              'In a lab or with research materials',
              'Talking to people directly, in a team',
              'With equipment, tools or on a production floor']},
      { q:'What comes naturally to you?',
        h:'Your superpower',
        opts:['Understanding technical systems',
              'Creating beautiful and original things',
              'Persuading others and negotiating',
              'Organising information and analysing',
              'Listening to people and understanding their needs',
              'Working with your hands and understanding mechanisms']},
      { q:'If money didn\'t matter — what would you do?',
        h:'Honest answer about your values',
        opts:['Write code, build technology or games',
              'Do creative work: draw, film, create',
              'Build a business or invest',
              'Study science, conduct research',
              'Teach, help, work with people',
              'Build, invent, engineer']}
    ]
  },

  // ──────────────────────────────────────────── DEUTSCH ──
  de: {
    tag:   'Berufsorientierung',
    title: 'Welches Berufsfeld passt zu dir?',
    sub:   '10 Fragen — finde deine Richtung',
    back:  '← Startseite',
    prog:  (n,t) => `Frage ${n} von ${t}`,
    resTag:'Deine Richtung',
    resSub:'Basierend auf deinen Antworten',
    goTest:'IT-Berufstest starten →', goTestCreative:'Kreativer Berufstest starten →', goTestBusiness:'Business-Berufstest starten →', goTestScience:'Wissenschaft & Medizin-Test starten →', goTestSocial:'Pädagogik & Gesellschaft-Test starten →', goTestEngineering:'Ingenieurwesen & Produktion-Test starten →',
    soon:  'Ein Test für dieses Berufsfeld kommt bald!',
    testSoon:'Test — bald verfügbar',
    alsoIt:'Wir empfehlen außerdem: IT-Berufstest',
    restart:'← Nochmal starten',
    multiHint:'Mehrfachauswahl möglich',
    domains:{
      it:          'IT & Technologie',
      creative:    'Kreativität & Medien',
      business:    'Business & Marketing',
      science:     'Naturwissenschaft & Medizin',
      social:      'Bildung & Soziales',
      engineering: 'Ingenieurwesen & Produktion'
    },
    domainDesc:{
      it:          'Programmierung, Daten, Cybersicherheit, DevOps',
      creative:    'Design, Video, Illustration, Animation',
      business:    'Marketing, Vertrieb, Unternehmertum, Management',
      science:     'Medizin, Biologie, Chemie, Physik, Forschung',
      social:      'Unterrichten, Psychologie, HR, Soziale Arbeit',
      engineering: 'Mechanik, Bauwesen, Elektronik, Robotik'
    },
    domainFull:{
      it:{
        who:'Für alle, die logisch denken, Probleme lieben und Systeme aufbauen wollen. Ideal, wenn dich Computer, Mathe oder Algorithmen faszinieren.',
        profs:'Entwickler (Frontend / Backend), Data Scientist, DevOps-Ingenieur, QA-Tester, Product Manager, Cybersecurity-Spezialist, UX/UI-Designer',
        start:'Starte mit Python oder JavaScript — erste Ergebnisse nach 1–2 Monaten. Probiere: python.org, javascript.info, freecodecamp.org'
      },
      creative:{
        who:'Für alle, die in Bildern denken, Schönheit spüren und Dinge schaffen wollen, die Menschen sehen, hören und fühlen.',
        profs:'Grafikdesigner, Videograf, Illustrator, Animator, Fotograf, Motion Designer, Content Creator, Art Director',
        start:'Starte mit Figma (kostenlos) oder zeichne 30 Illustrationen in 30 Tagen. Schau: figma.com, Adobe-Tutorials auf YouTube'
      },
      business:{
        who:'Für alle, die überzeugen können, Chancen sehen wo andere nichts bemerken, und gerne mit Menschen und Ergebnissen arbeiten.',
        profs:'Marketeer, SMM-Spezialist, Unternehmer, Ads-Spezialist, Projektmanager, Brand Manager, Texter, Werbungsanalyst',
        start:'Versuche etwas in sozialen Medien zu promoten oder lerne Marketing-Grundlagen. Buch: „Warum Dinge viral gehen" von Jonah Berger. Kurse: Coursera'
      },
      science:{
        who:'Für Neugierige, die gerne auf den Grund gehen, Experimente machen und verstehen wollen, wie die Welt von der Zelle bis zum Universum funktioniert.',
        profs:'Arzt, Wissenschaftler, Biotechnologe, Pharmazeut, Chemiker, Physiker, Epidemiologe, Bioinformatiker',
        start:'Vertiefe Biologie oder Chemie in der Schule. Lies Sachbücher: „Eine kurze Geschichte von fast allem" von Bill Bryson. Plattform: Khan Academy'
      },
      social:{
        who:'Für empathische Menschen, die gut zuhören können, andere verstehen und helfen wollen, das Leben anderer zu verbessern.',
        profs:'Lehrer, Psychologe, Sozialarbeiter, HR-Spezialist, Karriereberater, Coach, Logopäde',
        start:'Fange mit Ehrenamt an oder hilf jemandem, eine neue Fähigkeit zu lernen. Buch: „Emotionale Intelligenz" von Daniel Goleman'
      },
      engineering:{
        who:'Für alle, die gerne mit physischen Dingen arbeiten, greifbare Ergebnisse sehen und verstehen wollen, wie Mechanismen funktionieren.',
        profs:'Konstrukteur, Mechaniker, Architekt, Elektriker, Baufachmann, Robotik-Ingenieur, Automatisierungsingenieur, 3D-Modellierer',
        start:'Probiere Arduino oder 3D-Druck. Schau Engineering-YouTube-Kanäle. Buch: „Wie alles funktioniert" von Marshall Brain'
      }
    },
    qs:[
      { q:'Was fasziniert dich am meisten?',
        h:'Wähle die passendste Antwort',
        opts:['Am Computer etwas erstellen — Spiele, Webseiten, Apps',
              'Zeichnen, filmen, etwas Schönes schaffen',
              'Menschen organisieren, managen, Geld verdienen',
              'Natur erforschen, Experimente machen, heilen',
              'Mit Menschen kommunizieren, helfen, lehren',
              'Bauen, Dinge reparieren, mit den Händen arbeiten']},
      { q:'Welches Schulfach magst du am liebsten?',
        h:'Eine Antwort',
        opts:['Informatik oder Mathematik',
              'Kunst, Musik oder Literatur',
              'Sozialkunde oder Wirtschaft',
              'Biologie oder Chemie',
              'Geschichte, Sprachen oder Psychologie',
              'Physik oder Technik / Werken']},
      { q:'Was machst du in deiner Freizeit?',
        h:'Ehrlich — was machst du am häufigsten?',
        opts:['Programmieren, Spiele entwickeln oder Technologie erkunden',
              'Zeichnen, Videos drehen, Content erstellen',
              'Blog für Einnahmen betreiben oder nach Verdienstmöglichkeiten suchen',
              'Wissenschaftliches lesen, experimentieren, Natur erkunden',
              'Mit Kindern arbeiten, ehrenamtlich helfen',
              'Geräte zusammenbauen, auseinandernehmen oder reparieren']},
      { q:'Wie löst du Probleme am besten?',
        h:'Dein Denkstil',
        opts:['Durch Logik, Algorithmen und Struktur',
              'Durch Bilder, Ideen und kreative Lösungen',
              'Durch Verhandeln, Überzeugen und Menschenführung',
              'Durch Experimente, Daten und Analyse',
              'Durch Kommunikation und Einfühlungsvermögen',
              'Durch praktische Arbeit, Werkzeuge und körperliche Aktionen']},
      { q:'Du bekommst ein freies Projekt. Was wählst du?',
        h:'Erstes, was dir in den Sinn kommt',
        opts:['Ein Programm schreiben oder eine Webseite erstellen',
              'Ein Video drehen oder Illustrationen zeichnen',
              'Ein kleines Unternehmen oder eine Werbekampagne starten',
              'Ein Wissenschaftsexperiment durchführen',
              'Hilfe für Bedürftige organisieren',
              'Ein Gerät oder einen Mechanismus entwerfen']},
      { q:'Was ist dir in deinem Beruf am wichtigsten?',
        h:'Wichtigste Priorität wählen',
        opts:['Mit Technologie arbeiten und komplexe Probleme lösen',
              'Selbstausdruck und kreative Freiheit',
              'Karriere und gutes Einkommen',
              'Entdeckungen machen und die Welt verstehen',
              'Menschen helfen und eigene Wirkung sehen',
              'Das reale physische Ergebnis der eigenen Arbeit sehen']},
      { q:'Wo siehst du dich in 10 Jahren?',
        h:'Das ehrlichste Bild',
        opts:['Entwickler, Datenanalyst oder Cybersicherheitsexperte',
              'Designer, Videograf, Illustrator oder Animator',
              'Marketeer, Unternehmer oder Manager',
              'Arzt, Wissenschaftler, Apotheker oder Biotechnologe',
              'Lehrer, Psychologe, HR oder Sozialarbeiter',
              'Ingenieur, Bauexperte, Mechaniker oder Architekt']},
      { q:'Wie arbeitest du am liebsten?',
        h:'Ideale Arbeitsumgebung',
        opts:['Am Computer, mit Code und Daten',
              'Visuelle oder akustische Inhalte erstellen',
              'Menschen und Prozesse managen',
              'Im Labor oder mit Forschungsmaterialien',
              'Direkt mit Menschen sprechen, im Team',
              'Mit Geräten, Werkzeugen oder in der Produktion']},
      { q:'Was liegt dir besonders gut?',
        h:'Deine Superkraft',
        opts:['Technische Systeme verstehen',
              'Schöne und originelle Dinge erschaffen',
              'Andere überzeugen und verhandeln',
              'Informationen systematisieren und analysieren',
              'Menschen zuhören und ihre Bedürfnisse verstehen',
              'Mit den Händen arbeiten und Mechanismen verstehen']},
      { q:'Wenn Geld keine Rolle spielte — was würdest du tun?',
        h:'Ehrliche Antwort über deine Werte',
        opts:['Code schreiben, Technologie oder Spiele entwickeln',
              'Kreativ tätig sein: zeichnen, filmen, erschaffen',
              'Ein Unternehmen aufbauen oder investieren',
              'Wissenschaft studieren, forschen',
              'Unterrichten, helfen, mit Menschen arbeiten',
              'Bauen, erfinden, konstruieren']}
    ]
  },

  // ──────────────────────────────────────────── FRANÇAIS ──
  fr: {
    tag:   'Orientation professionnelle',
    title: 'Quel domaine te correspond?',
    sub:   '10 questions — découvre ta direction',
    back:  '← Accueil',
    prog:  (n,t) => `Question ${n} sur ${t}`,
    resTag:'Ta direction',
    resSub:'D\'après tes réponses',
    goTest:'Passer le test métiers IT →', goTestCreative:'Passer le test métiers créatifs →', goTestBusiness:'Passer le test métiers business →', goTestScience:'Passer le test sciences & médecine →', goTestSocial:'Passer le test éducation & société →', goTestEngineering:'Passer le test ingénierie & production →',
    soon:  'Un test pour ce domaine arrive bientôt !',
    testSoon:'Test — bientôt',
    alsoIt:'En attendant : test des métiers IT',
    restart:'← Recommencer',
    multiHint:'plusieurs choix possibles',
    domains:{
      it:          'IT & Technologie',
      creative:    'Créativité & Médias',
      business:    'Business & Marketing',
      science:     'Sciences & Médecine',
      social:      'Éducation & Social',
      engineering: 'Ingénierie & Production'
    },
    domainDesc:{
      it:          'Programmation, données, cybersécurité, DevOps',
      creative:    'Design, vidéo, illustration, animation',
      business:    'Marketing, ventes, entrepreneuriat, management',
      science:     'Médecine, biologie, chimie, physique, recherche',
      social:      'Enseignement, psychologie, RH, travail social',
      engineering: 'Mécanique, construction, électronique, robotique'
    },
    domainFull:{
      it:{
        who:'Pour ceux qui pensent logiquement, aiment résoudre des problèmes et construire des systèmes. Idéal si tu es passionné par les ordinateurs, les maths ou les algorithmes.',
        profs:'Développeur (frontend / backend), Data Scientist, Ingénieur DevOps, Testeur QA, Product Manager, Spécialiste cybersécurité, Designer UX/UI',
        start:'Commence avec Python ou JavaScript — les premiers résultats se voient en 1–2 mois. Essaie : python.org, javascript.info, freecodecamp.org'
      },
      creative:{
        who:'Pour ceux qui pensent en images, ressentent la beauté et veulent créer des choses que les gens voient, entendent et ressentent.',
        profs:'Graphiste, Vidéographe, Illustrateur, Animateur, Photographe, Motion Designer, Créateur de contenu, Directeur artistique',
        start:'Commence avec Figma (gratuit) ou essaie de dessiner 30 illustrations en 30 jours. Voir : figma.com, tutoriels Adobe sur YouTube'
      },
      business:{
        who:'Pour ceux qui savent convaincre, voient des opportunités là où d\'autres n\'en voient pas, et aiment travailler avec les gens et les résultats.',
        profs:'Marketeur, Spécialiste SMM, Entrepreneur, Spécialiste pub, Chef de projet, Brand Manager, Copywriter, Analyste publicitaire',
        start:'Essaie de promouvoir quelque chose sur les réseaux sociaux ou apprends les bases du marketing. Livre : « Contagieux » de Jonah Berger. Cours : Coursera'
      },
      science:{
        who:'Pour les curieux qui aiment aller au fond des choses, faire des expériences et comprendre comment le monde fonctionne — de la cellule à l\'univers.',
        profs:'Médecin, Chercheur scientifique, Biotechnologue, Pharmacien, Chimiste, Physicien, Épidémiologiste, Bioinformaticien',
        start:'Approfondis la biologie ou la chimie au lycée. Lis de la vulgarisation : « Une brève histoire de presque tout » de Bill Bryson. Plateforme : Khan Academy'
      },
      social:{
        who:'Pour les personnes empathiques qui savent écouter, comprennent les autres et veulent aider à améliorer la vie des gens.',
        profs:'Enseignant, Psychologue, Travailleur social, Spécialiste RH, Conseiller carrière, Coach, Orthophoniste',
        start:'Commence par le bénévolat ou aide quelqu\'un à acquérir une nouvelle compétence. Livre : « Intelligence émotionnelle » de Daniel Goleman'
      },
      engineering:{
        who:'Pour ceux qui aiment travailler avec des objets physiques, voir des résultats concrets et comprendre le fonctionnement des mécanismes.',
        profs:'Ingénieur concepteur, Mécanicien, Architecte, Électricien, Professionnel du BTP, Ingénieur robotique, Ingénieur automatisation, Modélisateur 3D',
        start:'Essaie Arduino ou l\'impression 3D. Regarde des chaînes YouTube d\'ingénierie. Livre : « Comment tout fonctionne » de Marshall Brain'
      }
    },
    qs:[
      { q:'Qu\'est-ce qui te fascine le plus?',
        h:'Choisis la réponse la plus proche',
        opts:['Créer des choses sur ordinateur — jeux, sites, applis',
              'Dessiner, filmer, créer quelque chose de beau',
              'Organiser des gens, gérer, gagner de l\'argent',
              'Étudier la nature, faire des expériences, soigner',
              'Communiquer avec les gens, aider, enseigner',
              'Construire, réparer des objets, travailler de ses mains']},
      { q:'Quelle matière préfères-tu à l\'école?',
        h:'Une seule réponse',
        opts:['Informatique ou mathématiques',
              'Arts plastiques, musique ou littérature',
              'Sciences sociales ou économie',
              'Biologie ou chimie',
              'Histoire, langues ou psychologie',
              'Physique ou technologie / travaux manuels']},
      { q:'Que fais-tu pendant ton temps libre?',
        h:'Soyons honnêtes — que fais-tu le plus souvent?',
        opts:['Coder, créer des jeux ou explorer les nouvelles techno',
              'Dessiner, tourner des vidéos, créer du contenu',
              'Tenir un blog pour gagner de l\'argent ou chercher des opportunités',
              'Lire de la science, expérimenter, explorer la nature',
              'Travailler avec des enfants, faire du bénévolat, aider',
              'Monter, démonter ou réparer des gadgets']},
      { q:'Comment résous-tu le mieux les problèmes?',
        h:'Ton style de pensée',
        opts:['Par la logique, les algorithmes et la structure',
              'Par les images, les idées et les solutions créatives',
              'Par la négociation, la persuasion et le management',
              'Par les expériences, les données et l\'analyse',
              'Par la communication et la compréhension des émotions',
              'Par la pratique, les outils et les actions physiques']},
      { q:'On te donne un projet libre. Que choisis-tu?',
        h:'Première idée qui te vient',
        opts:['Écrire un programme ou créer un site web',
              'Tourner une vidéo ou dessiner des illustrations',
              'Lancer une petite entreprise ou une campagne pub',
              'Faire une expérience scientifique',
              'Organiser de l\'aide pour ceux qui en ont besoin',
              'Concevoir un appareil ou un mécanisme']},
      { q:'Qu\'est-ce qui compte le plus pour toi dans ton futur métier?',
        h:'Choisis ta priorité principale',
        opts:['Travailler avec la technologie et résoudre des problèmes complexes',
              'L\'expression de soi et la liberté créative',
              'L\'évolution de carrière et un bon salaire',
              'Faire des découvertes et comprendre le monde',
              'Aider les gens et voir son impact',
              'Voir le résultat physique réel de son travail']},
      { q:'Où te vois-tu dans 10 ans?',
        h:'L\'image la plus honnête',
        opts:['Développeur, analyste de données ou expert en cybersécurité',
              'Designer, vidéographe, illustrateur ou animateur',
              'Marketeur, entrepreneur ou manager',
              'Médecin, scientifique, pharmacien ou biotechnologue',
              'Enseignant, psychologue, RH ou travailleur social',
              'Ingénieur, professionnel du bâtiment, mécanicien ou architecte']},
      { q:'Comment préfères-tu travailler?',
        h:'Environnement idéal',
        opts:['Sur ordinateur, avec du code et des données',
              'En créant du contenu visuel ou audio',
              'En gérant des personnes et des processus',
              'En laboratoire ou avec des matériaux de recherche',
              'En parlant directement aux gens, en équipe',
              'Avec des équipements, des outils ou en production']},
      { q:'Qu\'est-ce qui te vient naturellement?',
        h:'Ton super-pouvoir',
        opts:['Comprendre les systèmes techniques',
              'Créer des choses belles et originales',
              'Persuader les autres et négocier',
              'Organiser l\'information et analyser',
              'Écouter les gens et comprendre leurs besoins',
              'Travailler de ses mains et comprendre les mécanismes']},
      { q:'Si l\'argent n\'avait pas d\'importance — que ferais-tu?',
        h:'Réponse honnête sur tes valeurs',
        opts:['Écrire du code, créer des technologies ou des jeux',
              'Faire du travail créatif : dessiner, filmer, créer',
              'Créer une entreprise ou investir',
              'Étudier les sciences, faire de la recherche',
              'Enseigner, aider, travailler avec les gens',
              'Construire, inventer, concevoir']}
    ]
  },

  // ──────────────────────────────────────────── ESPAÑOL ──
  es: {
    tag:   'Orientación profesional',
    title: '¿Qué área te encaja?',
    sub:   '10 preguntas — descubre tu dirección',
    back:  '← Inicio',
    prog:  (n,t) => `Pregunta ${n} de ${t}`,
    resTag:'Tu dirección',
    resSub:'Según tus respuestas',
    goTest:'Hacer el test de carreras IT →', goTestCreative:'Hacer el test de carreras creativas →', goTestBusiness:'Hacer el test de carreras de negocios →', goTestScience:'Hacer el test de ciencia y medicina →', goTestSocial:'Hacer el test de educación y sociedad →', goTestEngineering:'Hacer el test de ingeniería y producción →',
    soon:  '¡Un test para esta área llegará pronto!',
    testSoon:'Test — próximamente',
    alsoIt:'Mientras tanto: test de carreras IT',
    restart:'← Repetir',
    multiHint:'puedes elegir varios',
    domains:{
      it:          'IT y Tecnología',
      creative:    'Creatividad y Medios',
      business:    'Negocios y Marketing',
      science:     'Ciencia y Medicina',
      social:      'Educación y Social',
      engineering: 'Ingeniería y Producción'
    },
    domainDesc:{
      it:          'Programación, datos, ciberseguridad, DevOps',
      creative:    'Diseño, video, ilustración, animación',
      business:    'Marketing, ventas, emprendimiento, gestión',
      science:     'Medicina, biología, química, física, investigación',
      social:      'Enseñanza, psicología, RRHH, trabajo social',
      engineering: 'Mecánica, construcción, electrónica, robótica'
    },
    domainFull:{
      it:{
        who:'Para quienes piensan lógicamente, aman resolver problemas y construir sistemas. Ideal si te interesan los ordenadores, las matemáticas o los algoritmos.',
        profs:'Desarrollador (frontend / backend), Data Scientist, Ingeniero DevOps, Tester QA, Product Manager, Especialista en ciberseguridad, Diseñador UX/UI',
        start:'Empieza con Python o JavaScript — verás resultados reales en 1–2 meses. Prueba: python.org, javascript.info, freecodecamp.org'
      },
      creative:{
        who:'Para quienes piensan en imágenes, sienten la belleza y quieren crear cosas que la gente vea, escuche y sienta.',
        profs:'Diseñador gráfico, Videógrafo, Ilustrador, Animador, Fotógrafo, Motion Designer, Creador de contenido, Director de arte',
        start:'Empieza con Figma (gratis) o intenta dibujar 30 ilustraciones en 30 días. Mira: figma.com, tutoriales de Adobe en YouTube'
      },
      business:{
        who:'Para quienes saben persuadir, ven oportunidades donde otros no las ven y disfrutan trabajar con personas y resultados.',
        profs:'Marketero, Especialista en redes sociales, Emprendedor, Especialista en publicidad, Gerente de proyecto, Brand Manager, Copywriter, Analista de publicidad',
        start:'Intenta promocionar algo en redes sociales o aprende los fundamentos del marketing. Libro: «Contagioso» de Jonah Berger. Cursos: Coursera'
      },
      science:{
        who:'Para los curiosos que aman llegar al fondo, hacer experimentos y entender cómo funciona el mundo, de la célula al universo.',
        profs:'Médico, Investigador científico, Biotecnólogo, Farmacéutico, Químico, Físico, Epidemiólogo, Bioinformático',
        start:'Profundiza en biología o química en el colegio. Lee divulgación científica: «Una breve historia de casi todo» de Bill Bryson. Plataforma: Khan Academy'
      },
      social:{
        who:'Para personas empáticas que saben escuchar, entienden a los demás y quieren mejorar la vida de alguien.',
        profs:'Maestro, Psicólogo, Trabajador social, Especialista en RRHH, Orientador laboral, Coach, Logopeda',
        start:'Empieza con el voluntariado o ayuda a alguien a aprender una habilidad nueva. Libro: «Inteligencia emocional» de Daniel Goleman'
      },
      engineering:{
        who:'Para quienes aman trabajar con cosas físicas, ver resultados tangibles y entender cómo funcionan los mecanismos.',
        profs:'Ingeniero de diseño, Mecánico, Arquitecto, Electricista, Profesional de la construcción, Ingeniero robótico, Ingeniero de automatización, Modelador 3D',
        start:'Prueba Arduino o impresión 3D. Mira canales de ingeniería en YouTube. Libro: «Cómo funciona todo» de Marshall Brain'
      }
    },
    qs:[
      { q:'¿Qué te fascina más?',
        h:'Elige la respuesta más cercana',
        opts:['Crear cosas en el ordenador — juegos, webs, apps',
              'Dibujar, filmar, crear algo bonito',
              'Organizar personas, gestionar, ganar dinero',
              'Estudiar la naturaleza, hacer experimentos, curar',
              'Comunicarse con personas, ayudar, enseñar',
              'Construir, reparar cosas, trabajar con las manos']},
      { q:'¿Qué asignatura te gusta más en el colegio?',
        h:'Una respuesta',
        opts:['Informática o matemáticas',
              'Arte, música o literatura',
              'Ciencias sociales o economía',
              'Biología o química',
              'Historia, idiomas o psicología',
              'Física o tecnología / taller']},
      { q:'¿Qué haces en tu tiempo libre?',
        h:'Sincero: ¿qué haces con más frecuencia?',
        opts:['Programar, hacer juegos o explorar tecnología',
              'Dibujar, grabar videos, crear contenido',
              'Llevar un blog para ganar dinero o buscar formas de ingresar',
              'Leer ciencia, experimentar, explorar la naturaleza',
              'Trabajar con niños, hacer voluntariado, ayudar',
              'Montar, desmontar o reparar gadgets']},
      { q:'¿Cómo resuelves mejor los problemas?',
        h:'Tu estilo de pensamiento',
        opts:['Mediante lógica, algoritmos y estructura',
              'Mediante imágenes, ideas y soluciones creativas',
              'Mediante negociación, persuasión y gestión de personas',
              'Mediante experimentos, datos y análisis',
              'Mediante comunicación y comprensión emocional',
              'Mediante práctica, herramientas y acciones físicas']},
      { q:'Te dan un proyecto libre. ¿Qué eliges?',
        h:'Lo primero que se te ocurre',
        opts:['Escribir un programa o crear una página web',
              'Grabar un video o dibujar ilustraciones',
              'Lanzar un pequeño negocio o campaña publicitaria',
              'Realizar un experimento científico',
              'Organizar ayuda para quienes lo necesitan',
              'Diseñar un dispositivo o mecanismo']},
      { q:'¿Qué valoras más en tu futuro trabajo?',
        h:'Elige la prioridad principal',
        opts:['Trabajar con tecnología y resolver problemas complejos',
              'Autoexpresión y libertad creativa',
              'Crecimiento profesional y buenos ingresos',
              'Hacer descubrimientos y comprender el mundo',
              'Ayudar a personas y ver tu impacto',
              'Ver el resultado físico real de tu trabajo']},
      { q:'¿Dónde te imaginas en 10 años?',
        h:'La imagen más honesta',
        opts:['Desarrollador, analista de datos o especialista en ciberseguridad',
              'Diseñador, videógrafo, ilustrador o animador',
              'Marketero, emprendedor o gestor',
              'Médico, científico, farmacéutico o biotecnólogo',
              'Profesor, psicólogo, RRHH o trabajador social',
              'Ingeniero, profesional de la construcción, mecánico o arquitecto']},
      { q:'¿Cómo prefieres trabajar?',
        h:'Entorno ideal',
        opts:['En el ordenador, con código y datos',
              'Creando contenido visual o de audio',
              'Gestionando personas y procesos',
              'En un laboratorio o con materiales de investigación',
              'Hablando directamente con personas, en equipo',
              'Con equipos, herramientas o en producción']},
      { q:'¿Qué te sale de forma natural?',
        h:'Tu superpoder',
        opts:['Entender sistemas técnicos',
              'Crear cosas bonitas y originales',
              'Persuadir a otros y negociar',
              'Organizar información y analizar',
              'Escuchar a las personas y entender sus necesidades',
              'Trabajar con las manos y entender mecanismos']},
      { q:'Si el dinero no importara — ¿qué harías?',
        h:'Respuesta honesta sobre tus valores',
        opts:['Escribir código, crear tecnología o juegos',
              'Hacer trabajo creativo: dibujar, filmar, crear',
              'Construir un negocio o invertir',
              'Estudiar ciencia, investigar',
              'Enseñar, ayudar, trabajar con personas',
              'Construir, inventar, diseñar']}
    ]
  },

  // ──────────────────────────────────────────── PORTUGUÊS ──
  pt: {
    tag:   'Orientação profissional',
    title: 'Qual área combina contigo?',
    sub:   '10 perguntas — descobre a tua direção',
    back:  '← Início',
    prog:  (n,t) => `Pergunta ${n} de ${t}`,
    resTag:'A tua direção',
    resSub:'Com base nas tuas respostas',
    goTest:'Fazer o teste de carreiras TI →', goTestCreative:'Fazer o teste de carreiras criativas →', goTestBusiness:'Fazer o teste de carreiras de negócios →', goTestScience:'Fazer o teste de ciências e medicina →', goTestSocial:'Fazer o teste de educação e sociedade →', goTestEngineering:'Fazer o teste de engenharia e produção →',
    soon:  'Um teste para esta área estará disponível em breve!',
    testSoon:'Teste — em breve',
    alsoIt:'Entretanto: teste de carreiras TI',
    restart:'← Repetir',
    multiHint:'podes escolher vários',
    domains:{
      it:          'TI & Tecnologia',
      creative:    'Criatividade & Média',
      business:    'Negócios & Marketing',
      science:     'Ciência & Medicina',
      social:      'Educação & Social',
      engineering: 'Engenharia & Produção'
    },
    domainDesc:{
      it:          'Programação, dados, cibersegurança, DevOps',
      creative:    'Design, vídeo, ilustração, animação',
      business:    'Marketing, vendas, empreendedorismo, gestão',
      science:     'Medicina, biologia, química, física, investigação',
      social:      'Ensino, psicologia, RH, trabalho social',
      engineering: 'Mecânica, construção, eletrónica, robótica'
    },
    domainFull:{
      it:{
        who:'Para quem pensa logicamente, adora resolver problemas e construir sistemas. Ideal se te interessas por computadores, matemática ou algoritmos.',
        profs:'Programador (frontend / backend), Data Scientist, Engenheiro DevOps, Testador QA, Product Manager, Especialista em cibersegurança, Designer UX/UI',
        start:'Começa com Python ou JavaScript — vês resultados reais em 1–2 meses. Experimenta: python.org, javascript.info, freecodecamp.org'
      },
      creative:{
        who:'Para quem pensa em imagens, sente a beleza e quer criar coisas que as pessoas vejam, ouçam e sintam.',
        profs:'Designer gráfico, Videógrafo, Ilustrador, Animador, Fotógrafo, Motion Designer, Criador de conteúdo, Diretor de arte',
        start:'Começa com Figma (grátis) ou tenta desenhar 30 ilustrações em 30 dias. Vê: figma.com, tutoriais Adobe no YouTube'
      },
      business:{
        who:'Para quem sabe persuadir, vê oportunidades onde outros não veem e gosta de trabalhar com pessoas e resultados.',
        profs:'Marketeer, Especialista SMM, Empreendedor, Especialista em publicidade, Gestor de projeto, Brand Manager, Copywriter, Analista de publicidade',
        start:'Tenta promover algo nas redes sociais ou aprende os fundamentos do marketing. Livro: «Contagioso» de Jonah Berger. Cursos: Coursera'
      },
      science:{
        who:'Para os curiosos que adoram ir ao fundo das questões, fazer experiências e perceber como o mundo funciona — da célula ao universo.',
        profs:'Médico, Cientista investigador, Biotecnólogo, Farmacêutico, Químico, Físico, Epidemiologista, Bioinformático',
        start:'Aprofunda biologia ou química na escola. Lê divulgação científica: «Uma Breve História de Quase Tudo» de Bill Bryson. Plataforma: Khan Academy'
      },
      social:{
        who:'Para pessoas empáticas que sabem ouvir, compreendem os outros e querem melhorar a vida de alguém.',
        profs:'Professor, Psicólogo, Assistente social, Especialista em RH, Consultor de carreira, Coach, Terapeuta da fala',
        start:'Começa com voluntariado ou ajuda alguém a aprender uma nova competência. Livro: «Inteligência Emocional» de Daniel Goleman'
      },
      engineering:{
        who:'Para quem gosta de trabalhar com coisas físicas, ver resultados tangíveis e perceber como os mecanismos funcionam.',
        profs:'Engenheiro de projeto, Mecânico, Arquiteto, Eletricista, Profissional de construção, Engenheiro de robótica, Engenheiro de automatização, Modelador 3D',
        start:'Experimenta Arduino ou impressão 3D. Vê canais de engenharia no YouTube. Livro: «Como Tudo Funciona» de Marshall Brain'
      }
    },
    qs:[
      { q:'O que te fascina mais?',
        h:'Escolhe a resposta mais próxima',
        opts:['Criar coisas no computador — jogos, sites, apps',
              'Desenhar, filmar, criar algo bonito',
              'Organizar pessoas, gerir, ganhar dinheiro',
              'Estudar a natureza, fazer experiências, curar',
              'Comunicar com pessoas, ajudar, ensinar',
              'Construir, reparar coisas, trabalhar com as mãos']},
      { q:'Qual é a tua disciplina favorita na escola?',
        h:'Uma resposta',
        opts:['Informática ou matemática',
              'Artes, música ou literatura',
              'Ciências sociais ou economia',
              'Biologia ou química',
              'História, línguas ou psicologia',
              'Física ou tecnologia / oficina']},
      { q:'O que fazes no teu tempo livre?',
        h:'Honesto — o que fazes com mais frequência?',
        opts:['Programar, fazer jogos ou explorar tecnologia',
              'Desenhar, gravar vídeos, criar conteúdo',
              'Gerir um blog para ganhar dinheiro ou procurar formas de ganhar',
              'Ler ciência, experimentar, explorar a natureza',
              'Trabalhar com crianças, ser voluntário, ajudar',
              'Montar, desmontar ou reparar gadgets']},
      { q:'Como resolves melhor os problemas?',
        h:'O teu estilo de pensamento',
        opts:['Através de lógica, algoritmos e estrutura',
              'Através de imagens, ideias e soluções criativas',
              'Através de negociação, persuasão e gestão de pessoas',
              'Através de experiências, dados e análise',
              'Através da comunicação e compreensão emocional',
              'Através da prática, ferramentas e ações físicas']},
      { q:'Deram-te um projeto livre. O que escolhes?',
        h:'Primeira ideia que te vem à cabeça',
        opts:['Escrever um programa ou criar um website',
              'Gravar um vídeo ou desenhar ilustrações',
              'Lançar um pequeno negócio ou campanha publicitária',
              'Realizar uma experiência científica',
              'Organizar ajuda para quem precisa',
              'Projetar um dispositivo ou mecanismo']},
      { q:'O que é mais importante para ti no trabalho futuro?',
        h:'Escolhe a prioridade principal',
        opts:['Trabalhar com tecnologia e resolver problemas complexos',
              'Autoexpressão e liberdade criativa',
              'Progressão na carreira e bons rendimentos',
              'Fazer descobertas e compreender o mundo',
              'Ajudar pessoas e ver o teu impacto',
              'Ver o resultado físico real do teu trabalho']},
      { q:'Onde te imaginas daqui a 10 anos?',
        h:'A imagem mais honesta',
        opts:['Programador, analista de dados ou especialista em cibersegurança',
              'Designer, videógrafo, ilustrador ou animador',
              'Marketeer, empreendedor ou gestor',
              'Médico, cientista, farmacêutico ou biotecnólogo',
              'Professor, psicólogo, RH ou assistente social',
              'Engenheiro, profissional de construção, mecânico ou arquiteto']},
      { q:'Como preferes trabalhar?',
        h:'Ambiente ideal',
        opts:['No computador, com código e dados',
              'Criando conteúdo visual ou áudio',
              'Gerindo pessoas e processos',
              'Em laboratório ou com materiais de investigação',
              'A falar diretamente com pessoas, em equipa',
              'Com equipamentos, ferramentas ou em produção']},
      { q:'O que te é natural?',
        h:'O teu superpoder',
        opts:['Compreender sistemas técnicos',
              'Criar coisas bonitas e originais',
              'Persuadir os outros e negociar',
              'Organizar informação e analisar',
              'Ouvir as pessoas e compreender as suas necessidades',
              'Trabalhar com as mãos e compreender mecanismos']},
      { q:'Se o dinheiro não importasse — o que farias?',
        h:'Resposta honesta sobre os teus valores',
        opts:['Escrever código, criar tecnologia ou jogos',
              'Fazer trabalho criativo: desenhar, filmar, criar',
              'Construir um negócio ou investir',
              'Estudar ciência, fazer investigação',
              'Ensinar, ajudar, trabalhar com pessoas',
              'Construir, inventar, projetar']}
    ]
  },

  // ──────────────────────────────────────────── ARABIC ──
  ar: {
    tag:   'التوجيه المهني',
    title: 'ما المجال الذي يناسبك؟',
    sub:   '١٠ أسئلة — اكتشف توجهك',
    back:  '→ الرئيسية',
    prog:  (n,t) => `السؤال ${n} من ${t}`,
    resTag:'توجهك',
    resSub:'بناءً على إجاباتك',
    goTest:'ابدأ اختبار مهن تقنية المعلومات ←', goTestCreative:'ابدأ اختبار المهن الإبداعية ←', goTestBusiness:'ابدأ اختبار مهن الأعمال ←', goTestScience:'ابدأ اختبار العلوم والطب ←', goTestSocial:'ابدأ اختبار التربية والمجتمع ←', goTestEngineering:'ابدأ اختبار الهندسة والإنتاج ←',
    soon:  'اختبار لهذا المجال قادم قريباً!',
    testSoon:'الاختبار قريباً',
    alsoIt:'في الوقت الحالي: اختبار مهن تقنية المعلومات',
    restart:'→ إعادة المحاولة',
    multiHint:'يمكنك اختيار أكثر من إجابة',
    domains:{
      it:          'تكنولوجيا المعلومات',
      creative:    'الإبداع والإعلام',
      business:    'الأعمال والتسويق',
      science:     'العلوم والطب',
      social:      'التعليم والمجتمع',
      engineering: 'الهندسة والإنتاج'
    },
    domainDesc:{
      it:          'البرمجة، البيانات، الأمن السيبراني، DevOps',
      creative:    'التصميم، الفيديو، الرسم، الرسوم المتحركة',
      business:    'التسويق، المبيعات، ريادة الأعمال، الإدارة',
      science:     'الطب، الأحياء، الكيمياء، الفيزياء، البحث',
      social:      'التدريس، علم النفس، الموارد البشرية، العمل الاجتماعي',
      engineering: 'الميكانيكا، البناء، الإلكترونيات، الروبوتيك'
    },
    domainFull:{
      it:{
        who:'لمن يفكر بمنطق، يحب حل المشكلات وبناء الأنظمة. مثالي إذا كنت مهتماً بالحواسيب أو الرياضيات أو الخوارزميات.',
        profs:'مطور (واجهة أمامية / خلفية)، عالم بيانات، مهندس DevOps، مختبر QA، مدير منتج، متخصص أمن سيبراني، مصمم UX/UI',
        start:'ابدأ بـ Python أو JavaScript — ستظهر النتائج الأولى خلال 1–2 أشهر. جرب: python.org، javascript.info، freecodecamp.org'
      },
      creative:{
        who:'لمن يفكر بالصور، يشعر بالجمال ويريد إنشاء أشياء يراها الناس ويسمعونها ويحسون بها.',
        profs:'مصمم جرافيك، مصور فيديو، رسام توضيحي، مُحرّك، مصور، مصمم حركة، صانع محتوى، مدير فني',
        start:'ابدأ بـ Figma (مجاناً) أو حاول رسم 30 رسماً في 30 يوماً. شاهد: figma.com، دروس Adobe على YouTube'
      },
      business:{
        who:'لمن يستطيع الإقناع، يرى الفرص حيث لا يراها الآخرون، ويحب العمل مع الناس والنتائج.',
        profs:'مسوّق، متخصص تسويق رقمي، رائد أعمال، متخصص إعلانات، مدير مشروع، مدير علامة تجارية، كاتب محتوى، محلل إعلانات',
        start:'جرب الترويج لشيء ما على وسائل التواصل أو تعلّم أساسيات التسويق. كتاب: «العدوى» لجونا بيرغر. دورات: Coursera'
      },
      science:{
        who:'للفضوليين الذين يحبون الوصول إلى جوهر الأشياء، إجراء التجارب وفهم كيفية عمل العالم من الخلية إلى الكون.',
        profs:'طبيب، باحث علمي، متخصص تقنية حيوية، صيدلاني، كيميائي، فيزيائي، وبائي، متخصص معلوماتية حيوية',
        start:'عمّق دراسة الأحياء أو الكيمياء في المدرسة. اقرأ: «تاريخ موجز لكل شيء تقريباً» لبيل برايسون. منصة: Khan Academy'
      },
      social:{
        who:'للأشخاص المتعاطفين الذين يُحسنون الاستماع، يفهمون الآخرين ويريدون المساعدة في تحسين حياة شخص ما.',
        profs:'معلم، معالج نفسي، أخصائي اجتماعي، متخصص موارد بشرية، مستشار مهني، مدرب، معالج نطق',
        start:'ابدأ بالتطوع أو ساعد شخصاً ما على تعلّم مهارة جديدة. كتاب: «الذكاء العاطفي» لدانيال غولمان'
      },
      engineering:{
        who:'لمن يحب العمل مع الأشياء المادية، رؤية النتائج الملموسة وفهم كيفية عمل الآليات.',
        profs:'مهندس تصميم، ميكانيكي، مهندس معماري، كهربائي، متخصص بناء، مهندس روبوتات، مهندس أتمتة، مصمم ثلاثي الأبعاد',
        start:'جرب Arduino أو الطباعة ثلاثية الأبعاد. شاهد قنوات الهندسة على YouTube. كتاب: «كيف تعمل الأشياء» لمارشال برين'
      }
    },
    qs:[
      { q:'ما الذي يأسرك أكثر من أي شيء آخر؟',
        h:'اختر أقرب إجابة',
        opts:['إنشاء أشياء على الحاسوب — ألعاب ومواقع وتطبيقات',
              'الرسم والتصوير وإنشاء شيء جميل',
              'تنظيم الناس والإدارة وكسب المال',
              'دراسة الطبيعة وإجراء التجارب والعلاج',
              'التواصل مع الناس ومساعدتهم والتعليم',
              'البناء وإصلاح الأشياء والعمل باليدين']},
      { q:'ما المادة الدراسية المفضلة لديك في المدرسة؟',
        h:'إجابة واحدة',
        opts:['علوم الحاسوب أو الرياضيات',
              'الفنون أو الموسيقى أو الأدب',
              'العلوم الاجتماعية أو الاقتصاد',
              'الأحياء أو الكيمياء',
              'التاريخ أو اللغات أو علم النفس',
              'الفيزياء أو التكنولوجيا / الأشغال اليدوية']},
      { q:'ماذا تفعل في وقت فراغك؟',
        h:'بصدق — ماذا تفعل في أغلب الأحيان؟',
        opts:['البرمجة وتطوير الألعاب واستكشاف التقنيات',
              'الرسم وتصوير الفيديوهات وإنشاء المحتوى',
              'إدارة مدونة للكسب أو البحث عن طرق للدخل',
              'قراءة العلوم والتجريب واستكشاف الطبيعة',
              'العمل مع الأطفال والتطوع ومساعدة الآخرين',
              'تجميع الأجهزة وتفكيكها وإصلاحها']},
      { q:'كيف تحل المشكلات بأفضل طريقة؟',
        h:'أسلوب تفكيرك',
        opts:['عبر المنطق والخوارزميات والهيكلة',
              'عبر الصور والأفكار والحلول الإبداعية',
              'عبر التفاوض والإقناع وإدارة الناس',
              'عبر التجارب والبيانات والتحليل',
              'عبر التواصل وفهم مشاعر الناس',
              'عبر الممارسة والأدوات والأفعال الجسدية']},
      { q:'أُعطيت مشروعاً حراً. ماذا تختار؟',
        h:'أول فكرة تخطر لك',
        opts:['كتابة برنامج أو إنشاء موقع ويب',
              'تصوير فيديو أو رسم سلسلة رسوم توضيحية',
              'إطلاق مشروع تجاري صغير أو حملة إعلانية',
              'إجراء تجربة علمية',
              'تنظيم مساعدة للمحتاجين',
              'تصميم جهاز أو آلية']},
      { q:'ما الأهم بالنسبة لك في عملك المستقبلي؟',
        h:'اختر الأولوية الرئيسية',
        opts:['العمل مع التكنولوجيا وحل المشكلات المعقدة',
              'التعبير عن الذات والحرية الإبداعية',
              'التقدم الوظيفي ودخل جيد',
              'إجراء اكتشافات وفهم العالم بعمق',
              'مساعدة الناس ورؤية أثرك الإيجابي',
              'رؤية النتيجة الفعلية الملموسة لعملك']},
      { q:'أين ترى نفسك بعد 10 سنوات؟',
        h:'الصورة الأكثر صدقاً',
        opts:['مطور أو محلل بيانات أو متخصص في الأمن السيبراني',
              'مصمم أو مصوّر فيديو أو مُصوِّر أو رسّام متحرك',
              'مسوّق أو رائد أعمال أو مدير',
              'طبيب أو عالم أو صيدلاني أو متخصص في التقنية الحيوية',
              'معلم أو معالج نفسي أو متخصص موارد بشرية أو عامل اجتماعي',
              'مهندس أو متخصص بناء أو ميكانيكي أو معماري']},
      { q:'كيف تفضل العمل؟',
        h:'البيئة المثالية',
        opts:['أمام الحاسوب مع الكود والبيانات',
              'إنشاء محتوى مرئي أو صوتي',
              'إدارة الناس والعمليات',
              'في مختبر أو مع مواد بحثية',
              'التحدث مباشرة مع الناس وضمن فريق',
              'مع المعدات والأدوات أو في بيئة الإنتاج']},
      { q:'ما الذي يأتيك بشكل طبيعي؟',
        h:'قوتك الخارقة',
        opts:['فهم الأنظمة التقنية',
              'إنشاء أشياء جميلة وأصيلة',
              'إقناع الآخرين والتفاوض',
              'تنظيم المعلومات وتحليلها',
              'الاستماع للناس وفهم احتياجاتهم',
              'العمل باليدين وفهم الآليات']},
      { q:'لو لم يكن المال مهماً — ماذا كنت ستفعل؟',
        h:'إجابة صادقة عن قيمك',
        opts:['كتابة الكود وبناء التكنولوجيا أو الألعاب',
              'العمل الإبداعي: الرسم والتصوير والإنشاء',
              'بناء مشروع تجاري أو الاستثمار',
              'دراسة العلوم وإجراء الأبحاث',
              'التعليم والمساعدة والعمل مع الناس',
              'البناء والاختراع والتصميم الهندسي']}
    ]
  },

  // ──────────────────────────────────────────── HEBREW ──
  he: {
    tag:   'אוריינטציה מקצועית',
    title: 'איזה תחום מתאים לך?',
    sub:   '10 שאלות — גלה את הכיוון שלך',
    back:  '← דף הבית',
    prog:  (n,t) => `שאלה ${n} מתוך ${t}`,
    resTag:'הכיוון שלך',
    resSub:'בהתבסס על תשובותיך',
    goTest:'התחל את מבחן מקצועות ה-IT ←', goTestCreative:'התחל את מבחן המקצועות היצירתיים ←', goTestBusiness:'התחל את מבחן מקצועות העסקים ←', goTestScience:'התחל את מבחן מדע ורפואה ←', goTestSocial:'התחל את מבחן החינוך והחברה ←', goTestEngineering:'התחל את מבחן ההנדסה והייצור ←',
    soon:  'מבחן לתחום זה יגיע בקרוב!',
    testSoon:'מבחן — בקרוב',
    alsoIt:'בינתיים: מבחן מקצועות ה-IT',
    restart:'← נסה שוב',
    multiHint:'ניתן לבחור מספר תשובות',
    domains:{
      it:          'IT וטכנולוגיה',
      creative:    'יצירתיות ומדיה',
      business:    'עסקים ושיווק',
      science:     'מדע ורפואה',
      social:      'חינוך וחברה',
      engineering: 'הנדסה וייצור'
    },
    domainDesc:{
      it:          'תכנות, נתונים, אבטחת סייבר, DevOps',
      creative:    'עיצוב, וידאו, איור, אנימציה',
      business:    'שיווק, מכירות, יזמות, ניהול',
      science:     'רפואה, ביולוגיה, כימיה, פיזיקה, מחקר',
      social:      'הוראה, פסיכולוגיה, משאבי אנוש, עבודה סוציאלית',
      engineering: 'מכניקה, בנייה, אלקטרוניקה, רובוטיקה'
    },
    domainFull:{
      it:{
        who:'למי שחושב בצורה לוגית, אוהב לפתור בעיות ולבנות מערכות. מתאים במיוחד אם מחשבים, מתמטיקה או אלגוריתמים מעניינים אותך.',
        profs:'מפתח (frontend / backend), מדען נתונים, מהנדס DevOps, בודק QA, מנהל מוצר, מומחה אבטחת סייבר, מעצב UX/UI',
        start:'התחל עם Python או JavaScript — תראה תוצאות ראשונות תוך 1–2 חודשים. נסה: python.org, javascript.info, freecodecamp.org'
      },
      creative:{
        who:'למי שחושב בתמונות, חש את היופי ורוצה ליצור דברים שאנשים רואים, שומעים ומרגישים.',
        profs:'מעצב גרפי, צלם וידאו, מאייר, מאניימטור, צלם, מעצב תנועה, יוצר תוכן, דירקטור אמנותי',
        start:'התחל עם Figma (בחינם) או נסה לצייר 30 איורים ב-30 ימים. ראה: figma.com, הדרכות Adobe ב-YouTube'
      },
      business:{
        who:'למי שיודע לשכנע, רואה הזדמנויות שאחרים מפספסים, ואוהב לעבוד עם אנשים ותוצאות.',
        profs:'משווק, מומחה רשתות חברתיות, יזם, מומחה פרסום, מנהל פרויקט, מנהל מותג, קופירייטר, אנליסט פרסום',
        start:'נסה לקדם משהו ברשתות החברתיות או למד יסודות שיווק. ספר: «מדבק» של יונה ברגר. קורסים: Coursera'
      },
      science:{
        who:'לסקרנים שאוהבים להגיע לשורש הדברים, לבצע ניסויים ולהבין איך העולם עובד — מהתא ועד היקום.',
        profs:'רופא, חוקר מדעי, ביוטכנולוג, רוקח, כימאי, פיזיקאי, אפידמיולוג, ביואינפורמטיקאי',
        start:'העמק את הביולוגיה או הכימיה בבית הספר. קרא: «היסטוריה קצרה של כמעט הכל» של ביל ברייסון. פלטפורמה: Khan Academy'
      },
      social:{
        who:'לאנשים אמפתיים שיודעים להקשיב, מבינים אחרים ורוצים לעזור לשפר את חייהם של אנשים.',
        profs:'מורה, פסיכולוג, עובד סוציאלי, מומחה משאבי אנוש, יועץ קריירה, מאמן, קלינאי תקשורת',
        start:'התחל בהתנדבות או עזור למישהו ללמוד מיומנות חדשה. ספר: «אינטליגנציה רגשית» של דניאל גולמן'
      },
      engineering:{
        who:'למי שאוהב לעבוד עם דברים פיזיים, לראות תוצאות מוחשיות ולהבין איך מנגנונים עובדים.',
        profs:'מהנדס תכנון, מכונאי, אדריכל, חשמלאי, איש בנייה, מהנדס רובוטיקה, מהנדס אוטומציה, מדגמן תלת-ממד',
        start:'נסה Arduino או הדפסה תלת-ממדית. צפה בערוצי הנדסה ב-YouTube. ספר: «איך הכל עובד» של מרשל ברין'
      }
    },
    qs:[
      { q:'מה מרתק אותך ביותר?',
        h:'בחר את התשובה הקרובה ביותר',
        opts:['ליצור דברים במחשב — משחקים, אתרים, אפליקציות',
              'לצייר, לצלם, ליצור משהו יפה',
              'לארגן אנשים, לנהל, להרוויח כסף',
              'לחקור טבע, לעשות ניסויים, לרפא',
              'לתקשר עם אנשים, לעזור, ללמד',
              'לבנות, לתקן דברים, לעבוד עם הידיים']},
      { q:'איזה מקצוע בבית הספר אוהב הכי הרבה?',
        h:'תשובה אחת',
        opts:['מדעי המחשב או מתמטיקה',
              'אמנות, מוזיקה או ספרות',
              'לימודי חברה או כלכלה',
              'ביולוגיה או כימיה',
              'היסטוריה, שפות או פסיכולוגיה',
              'פיזיקה או טכנולוגיה / עבודת כפיים']},
      { q:'מה אתה עושה בזמן הפנוי?',
        h:'בכנות — מה אתה עושה הכי הרבה?',
        opts:['מתכנת, מפתח משחקים או חוקר טכנולוגיות',
              'מצייר, מצלם וידאו, יוצר תוכן',
              'מנהל בלוג להכנסה או מחפש דרכים להרוויח',
              'קורא מדע, מבצע ניסויים, חוקר טבע',
              'עובד עם ילדים, מתנדב, עוזר לאחרים',
              'מרכיב, מפרק או מתקן גאדג\'טים']},
      { q:'כיצד אתה פותר בעיות בצורה הטובה ביותר?',
        h:'סגנון החשיבה שלך',
        opts:['באמצעות לוגיקה, אלגוריתמים ומבנה',
              'באמצעות תמונות, רעיונות ופתרונות יצירתיים',
              'באמצעות משא ומתן, שכנוע וניהול אנשים',
              'באמצעות ניסויים, נתונים וניתוח',
              'באמצעות תקשורת והבנת רגשות',
              'באמצעות תרגול, כלים ופעולות פיזיות']},
      { q:'קיבלת פרויקט חופשי. מה תבחר?',
        h:'הדבר הראשון שעולה בראשך',
        opts:['לכתוב תוכנה או לבנות אתר אינטרנט',
              'לצלם וידאו או לצייר סדרת איורים',
              'להשיק עסק קטן או קמפיין פרסומי',
              'לבצע ניסוי מדעי',
              'לארגן עזרה לנזקקים',
              'לתכנן מכשיר או מנגנון']},
      { q:'מה הכי חשוב לך בעבודה העתידית?',
        h:'בחר את העדיפות העיקרית',
        opts:['לעבוד עם טכנולוגיה ולפתור בעיות מורכבות',
              'הבעה עצמית וחופש יצירתי',
              'קידום בקריירה והכנסה טובה',
              'לעשות גילויים ולהבין את העולם לעומק',
              'לעזור לאנשים ולראות את ההשפעה שלך',
              'לראות את התוצאה הפיזית האמיתית של העבודה שלך']},
      { q:'איפה אתה רואה את עצמך בעוד 10 שנים?',
        h:'התמונה הכי כנה',
        opts:['מפתח, אנליסט נתונים או מומחה אבטחת סייבר',
              'מעצב, צלם וידאו, מאייר או מאניים',
              'משווק, יזם או מנהל',
              'רופא, מדען, פרמצבט או מומחה ביוטכנולוגיה',
              'מורה, פסיכולוג, משאבי אנוש או עובד סוציאלי',
              'מהנדס, איש בנייה, מכונאי או אדריכל']},
      { q:'כיצד אתה מעדיף לעבוד?',
        h:'הסביבה האידיאלית',
        opts:['מול המחשב, עם קוד ונתונים',
              'יצירת תוכן ויזואלי או קולי',
              'ניהול אנשים ותהליכים',
              'במעבדה או עם חומרי מחקר',
              'שיחה ישירה עם אנשים, בצוות',
              'עם ציוד, כלים או בסביבת ייצור']},
      { q:'מה בא לך בטבעיות?',
        h:'הסופר-כוח שלך',
        opts:['הבנת מערכות טכניות',
              'יצירת דברים יפים ומקוריים',
              'שכנוע אחרים וניהול משא ומתן',
              'ארגון מידע וניתוחו',
              'הקשבה לאנשים והבנת צרכיהם',
              'עבודה עם הידיים והבנת מנגנונים']},
      { q:'אם כסף לא היה משנה — מה היית עושה?',
        h:'תשובה כנה על הערכים שלך',
        opts:['לכתוב קוד, לפתח טכנולוגיה או משחקים',
              'לעשות עבודה יצירתית: לצייר, לצלם, ליצור',
              'לבנות עסק או להשקיע',
              'ללמוד מדע, לעשות מחקר',
              'ללמד, לעזור, לעבוד עם אנשים',
              'לבנות, להמציא, לתכנן']}
    ]
  },
  // ──────────────────────────────────────────── 中文 ──
  zh: {
    tag:   '职业方向测试',
    title: '哪个领域最适合你？',
    sub:   '10道题——发现你的方向',
    back:  '← 首页',
    prog:  (n,t) => `第 ${n} 题，共 ${t} 题`,
    resTag:'你的方向',
    resSub:'根据你的答案',
    goTest:'参加IT职业测试 →', goTestCreative:'参加创意职业测试 →', goTestBusiness:'参加商业职业测试 →', goTestScience:'参加科学与医学测试 →', goTestSocial:'参加教育与社会测试 →', goTestEngineering:'参加工程与生产测试 →',
    soon:  '该领域的测试即将上线！',
    testSoon:'测试——即将推出',
    alsoIt:'同时推荐：IT职业测试',
    restart:'← 重新测试',
    multiHint:'可以多选',
    domains:{
      it:          'IT与科技',
      creative:    '创意与媒体',
      business:    '商业与营销',
      science:     '科学与医学',
      social:      '教育与社会',
      engineering: '工程与生产'
    },
    domainDesc:{
      it:          '编程、数据、网络安全、DevOps',
      creative:    '设计、视频、插画、动画',
      business:    '营销、销售、创业、管理',
      science:     '医学、生物、化学、物理、研究',
      social:      '教学、心理学、HR、社会工作',
      engineering: '机械、建筑、电子、机器人'
    },
    domainFull:{
      it:{
        who:'适合那些逻辑思维强、喜欢解决问题和构建系统的人。如果你对计算机、数学或算法感兴趣，这是绝佳选择。',
        profs:'开发工程师（前端/后端）、数据科学家、DevOps工程师、QA测试员、产品经理、网络安全专家、UX/UI设计师',
        start:'从Python或JavaScript开始——1-2个月内就能看到真实成果。试试：python.org、javascript.info、freecodecamp.org'
      },
      creative:{
        who:'适合那些以图像思考、感受美的人，他们想创造别人看到、听到和感受到的东西。适合内向者和外向者。',
        profs:'平面设计师、摄像师、插画师、动画师、摄影师、动态设计师、内容创作者、艺术总监',
        start:'从Figma（免费）开始，或者尝试30天画30幅插画。参考：figma.com、YouTube上的Adobe教程'
      },
      business:{
        who:'适合善于说服、能在别人看不到的地方发现机会、喜欢与人合作并注重结果的人。',
        profs:'营销人、SMM专员、创业者、广告专员、项目经理、品牌经理、文案、广告分析师',
        start:'尝试在社交媒体上推广某样东西，或学习营销基础。书籍：约拿·伯杰的《疯传》。课程：Coursera、HubSpot Academy'
      },
      science:{
        who:'适合喜欢追根究底、做实验，以及想理解世界运作方式——从细胞到宇宙——的好奇者。',
        profs:'医生、研究科学家、生物技术学家、药剂师、化学家、物理学家、流行病学家、生物信息学家',
        start:'在学校深化生物或化学。阅读科普：比尔·布莱森的《万物简史》。平台：Khan Academy'
      },
      social:{
        who:'适合善于倾听、理解他人、想帮助别人让生活变得更好的有同理心的人。',
        profs:'教师、心理学家、社会工作者、HR专员、职业顾问、教练、语言治疗师',
        start:'从志愿服务或帮助别人开始。书籍：丹尼尔·戈尔曼的《情绪智力》。网站：coursera.org/social-science'
      },
      engineering:{
        who:'适合喜欢与实物打交道、看到有形成果、并想理解机构如何工作的人。',
        profs:'设计工程师、机械师、建筑师、电气工程师、建筑专业人员、机器人工程师、自动化工程师、3D建模师',
        start:'尝试Arduino或3D打印。观看工程类YouTube频道。书籍：马歇尔·布雷恩的《万物运作原理》'
      }
    },
    qs:[
      { q:'什么最让你着迷？',
        h:'选择最接近的答案',
        opts:['在电脑上创造东西——游戏、网站、应用',
              '画画、拍视频、创作美的东西',
              '组织人员、管理、赚钱',
              '研究自然、做实验、治病救人',
              '与人交流、帮助他人、教导别人',
              '建造、修理东西、动手操作']},
      { q:'你最喜欢哪门学科？',
        h:'一个答案',
        opts:['计算机或数学',
              '美术、音乐或文学',
              '社会学或经济学',
              '生物或化学',
              '历史、语言或心理学',
              '物理或技术/工艺']},
      { q:'你在业余时间做什么？',
        h:'诚实地说——你最常做什么？',
        opts:['编程、做游戏或探索新技术',
              '画画、拍视频、创作内容',
              '为了收入运营博客或寻找赚钱方式',
              '阅读科学内容、做实验、探索自然',
              '带孩子、做志愿者、帮助他人',
              '组装、拆解或修理小设备']},
      { q:'你最擅长用什么方式解决问题？',
        h:'你的思维风格',
        opts:['通过逻辑、算法和结构',
              '通过图像、创意和创造性方案',
              '通过谈判、说服和人员管理',
              '通过实验、数据和分析',
              '通过沟通和理解情感',
              '通过实践、工具和动手操作']},
      { q:'你得到一个自由项目。你选择什么？',
        h:'第一个想到的',
        opts:['写一个程序或做一个网站',
              '拍一个视频或画一系列插画',
              '创办一个小生意或广告活动',
              '做一个科学实验',
              '为有需要的人组织帮助',
              '设计一个装置或机构']},
      { q:'对你来说，未来工作中什么最重要？',
        h:'选择最优先的',
        opts:['使用技术并解决复杂问题',
              '自我表达和创作自由',
              '职业发展和良好收入',
              '做出发现并理解世界',
              '帮助他人并看到自己的影响',
              '看到工作的实实在在的成果']},
      { q:'10年后你看到自己在哪里？',
        h:'最诚实的画面',
        opts:['开发工程师、数据分析师或网络安全专家',
              '设计师、摄像师、插画师或动画师',
              '营销人、创业者或经理',
              '医生、科学家、药剂师或生物技术专家',
              '教师、心理学家、HR或社会工作者',
              '工程师、建筑专业人员、机械师或建筑师']},
      { q:'你更喜欢怎样工作？',
        h:'理想的环境',
        opts:['在电脑前，用代码和数据',
              '创作视觉或音频内容',
              '管理人员和流程',
              '在实验室或使用研究材料',
              '直接与人交谈、团队合作',
              '使用设备、工具或在生产车间']},
      { q:'什么对你来说是自然而然的？',
        h:'你的超能力',
        opts:['理解技术系统',
              '创造美丽和原创的东西',
              '说服他人和谈判',
              '组织信息和分析',
              '倾听他人并理解他们的需求',
              '动手工作并理解机构']},
      { q:'如果钱不是问题——你会做什么？',
        h:'关于你价值观的诚实回答',
        opts:['写代码、构建技术或游戏',
              '做创意工作：画画、拍视频、创作',
              '创业或投资',
              '研究科学、开展研究',
              '教导、帮助、与人合作',
              '建造、发明、做工程']}
    ]
  },

};