// ─── Language: EN ─────────────────────────────────────────────────
// Load order: lang-base.js → lang-en.js

I18N.en = {
  dir:'ltr', flag:'🇬🇧', name:'EN',
  ui:{
    tag:'Test for teenagers',
    title:'Which IT career suits you?',
    subtitle:'10 multiple-choice questions — find your direction in tech',
    hint:'You can select multiple answers',
    next:'Next →', back:'← Back', finish:'See my result →',
    resTag:'Result', resSub:'Here\'s what fits you best',
    winBadge:'Your career', othTitle:'Other matching directions',
    lblStart:'How to start', lblDay:'Typical day', lblTools:'Key tools',
    lblSalary:'Salary', lblEx:'What you\'ll build', restart:'↺ Retake test',
    footer:'Free test · No sign-up · Instant result', done:'✓ Done',
    l2btn:'🔍 Find your specialization →',
    l2back:'← Back to result', l2resTag:'Your specialization',
    l2resSub:'Here\'s your direction within the profession',
    l2othTitle:'Other matching specializations',
    l2toL1:'← Back to main result', hint2:'You can select multiple answers',
    l2direct:'Already know your profession? Start with the specialization test:',
    l2directBack:'← Back to start'
  },
  qs:[
    {t:'What do you like to do in your free time?',o:['Play video games (PC, console, mobile)','Draw, sculpt, create designs','Take apart or repair gadgets','Solve puzzles, riddles, strategies','Chat and help other people','Watch videos about tech and programming','Create something of your own: blog, video, website','Read about history, science, facts']},
    {t:'Which school subjects come easily and do you enjoy?',o:['Math and algebra','Physics','Computer science / IT','Art / drawing / technical drawing','Literature and language','Biology / chemistry','Foreign languages','History / social studies']},
    {t:'Which of these describes you best?',o:['I notice mistakes and inaccuracies everywhere','I love when results are visible right away — clear and beautiful','I can work a long time on a tough problem','I\'m good at explaining complex things simply','I want to understand how everything works inside','I love having data to draw conclusions from','I want to create things thousands of people will use','I easily switch between different tasks']},
    {t:'You open a cool app — what grabs your attention first?',o:['How beautiful and user-friendly the design is','How fast it runs without lagging','Smart features: AI, analytics, suggestions','Fun gameplay or animations','Whether there are security vulnerabilities','Whether everything is clear without instructions','How developers solved the user\'s problem']},
    {t:'Which project would you choose for a school fair?',o:['A website or mobile app','A game — browser-based or mobile','Data analysis + visualization (charts, insights)','Security test — try to hack the class website','A beautiful infographic or UI mockup','Organize a team and plan everything out','Automate something boring (bot, script)','Write a test plan for someone else\'s project']},
    {t:'Imagine you work at an IT company. What do you enjoy doing?',o:['I draw mockups and design interfaces','I write code that runs on the server','I build beautiful pages and buttons','I hunt for security holes before hackers do','I keep servers from going down 24/7','I analyze data and build predictive models','I find bugs and write test cases','I talk to clients and assign tasks to the team']},
    {t:'What really annoys you or seems boring?',o:['Sitting on one task for a long time with no visible result','Lots of meetings and communication','Doing the same thing over and over by instructions','Paying attention to details and documenting','Drawing and thinking about visual appearance','Digging through someone else\'s code','None of these, everything\'s fine']},
    {t:'What scares you or seems difficult?',o:['A lot of math and formulas','Being responsible for decisions','Communicating with a big team every day','Not seeing the result of your work for months','Working with unclear code without documentation','None of these, everything\'s fine']},
    {t:'What matters most to you in a future job?',o:['High salary','Creative freedom','Stability and clear tasks','Influencing the product and making decisions','Always new challenges, no routine','Seeing the result of your work with your own eyes','Working at a famous cool company']},
    {t:'What have you already tried or want to try?',o:['Build a website or landing page','Write a bot (Telegram, Discord)','Play in Roblox Studio or Unity','Design in Figma or Canva','Solve problems on Codeforces / Leetcode','Look at CTF security challenges','Analyze data in Excel or Python','Haven\'t tried anything yet']}
  ],
  prof:{
    frontend:{name:'Frontend Developer',desc:'Builds everything users see: websites, interfaces, animations.',detail:'A frontend developer brings designs to life in the browser. You write HTML, CSS and JavaScript — and immediately see the result. Modern frontend devs use frameworks like React or Vue. The job sits at the intersection of design and engineering: you need both visual sense and technical thinking.',day:'Code review, implement a new component from Figma mockup, fix mobile layout, cross-browser testing, deploy.',examples:'Netflix UI, Google Search, Instagram feed',start:['HTML + CSS — freecodecamp.org (free)','JavaScript — javascript.info','React — react.dev (official)']},
    backend:{name:'Backend Developer',desc:'Writes the "brain" of apps: logic, databases, APIs.',detail:'Backend is everything happening under the hood. When you log in, make a purchase or get a notification — that\'s backend. You design databases, write server logic, build APIs. One of the highest-paid specializations in IT.',day:'Design API endpoints, optimize SQL queries, write unit tests, code review, sync with frontend.',examples:'WhatsApp servers, Spotify recommendation engine, bank payment processing',start:['Python — python.org','SQL — sqlbolt.com (free)','First project: build a Telegram bot']},
    design:{name:'UI/UX Designer',desc:'Decides how a product looks and feels.',detail:'A UI/UX designer shapes the user experience. UI is the visual appearance, UX is how it feels to use. You research user needs, create wireframes and prototypes. Good design isn\'t just beautiful — it\'s intuitive and clear. Psychology matters as much as aesthetics.',day:'User interviews, wireframes in Figma, prototype a new feature, align with developers, A/B test.',examples:'Apple iOS design, Airbnb booking flow, Spotify interface',start:['Figma — figma.com (free)','UX Foundations on Coursera','Recreate an existing app\'s design as practice']},
    gamedev:{name:'Game Developer',desc:'Creates games — from concept to code and gameplay.',detail:'A game developer is programmer, designer and storyteller in one. You implement game mechanics, physics and enemy AI. Gamedev is one of the most exciting areas of IT. Many developers start by creating mods for their favorite games.',day:'Implement a new jump mechanic in Unity, tune physics, test a level, optimize FPS.',examples:'Minecraft, Fortnite, Among Us, Roblox',start:['Unity Learn — learn.unity.com (free)','Roblox Studio — free with built-in audience','Godot — godotengine.org (free)']},
    data:{name:'Data Scientist / ML Engineer',desc:'Analyzes data, builds AI models, finds hidden patterns.',detail:'A data scientist works with large datasets to find patterns and drive decisions. ML engineers build machine learning models — the ones behind YouTube recommendations and ChatGPT. One of the fastest-growing, highest-paid fields in tech.',day:'Load and clean data, build a prediction model, evaluate accuracy, visualize results for the team.',examples:'ChatGPT, Netflix & YouTube recommendations, bank fraud detection, Siri',start:['Python — kaggle.com/learn (free)','Compete on Kaggle.com','fast.ai — free practical course']},
    security:{name:'Cybersecurity Specialist',desc:'Finds vulnerabilities in systems and protects them.',detail:'A cybersecurity specialist is a legal hacker. Your job: find vulnerabilities before attackers do. You run penetration tests, analyze malware, build defense systems. Demand for security professionals keeps growing.',day:'Scan system for vulnerabilities, penetration test, write report, monitor suspicious activity.',examples:'Google & Facebook bug bounty programs, bank security, cyber incident investigation',start:['TryHackMe.com — free, gamified format','picoCTF — beginner CTF competitions','Learn Linux basics first']},
    devops:{name:'DevOps / SRE Engineer',desc:'Keeps services running smoothly and automates everything.',detail:'A DevOps engineer bridges developers and servers. You set up CI/CD pipelines, manage cloud infrastructure, ensure 24/7 uptime. Without DevOps, developers\' code never reaches users.',day:'Configure GitHub Actions, monitor metrics in Grafana, investigate an outage, update Kubernetes cluster.',examples:'Netflix infrastructure, Google SRE team, AWS/Azure/GCP cloud',start:['Linux — linuxjourney.com (free)','Docker — docs.docker.com/get-started','AWS Free Tier — aws.amazon.com/free']},
    qa:{name:'QA Engineer (Tester)',desc:'Finds bugs before users do.',detail:'A QA engineer guarantees software quality. You create test cases, find bugs and automate checks. QA is a great entry point into IT — attention to detail and logical thinking matter more than coding at first.',day:'Study a ticket in Jira, write test cases, manual testing, file a bug report, run automated tests.',examples:'Testing every iOS update, bank transaction verification',start:['Software Testing basics — guru99.com (free)','Postman — api.postman.com (free)','Find bugs on any website — that\'s already practice']},
    pm:{name:'Product Manager',desc:'Leads product development: sets tasks, makes decisions, aligns the team.',detail:'A product manager is the "CEO of the product." You decide what the team builds and why. You constantly communicate: with developers, designers, marketing, clients. PMs don\'t write code but must understand tech enough for meaningful conversations.',day:'Team standup, user interview, write a feature spec, prioritize backlog, analyze product metrics.',examples:'The person who defined the original iPhone features; team behind TikTok\'s algorithm',start:['"Inspired" by Marty Cagan (book)','Product Manager course on Coursera','Describe a product you want to build — that\'s already PM thinking']}
  }
};

GLOSSARY.en = {
'API':          'Application Programming Interface — how programs communicate with each other over the internet',
    'SPA':          'Single Page Application — a website that doesn\'t fully reload, like Gmail or Trello',
    'CSS':          'Cascading Style Sheets — describe how a page looks: colors, fonts, spacing',
    'HTML':         'HyperText Markup Language — defines the structure of a webpage: headings, buttons, links',
    'SQL':          'Structured Query Language — used to query databases. Example: SELECT * FROM users',
    'REST':         'Representational State Transfer — an architectural style for how APIs communicate',
    'CI/CD':        'Continuous Integration/Delivery — automatic testing and deployment on every code change',
    'SRE':          'Site Reliability Engineering — engineers who keep services running 24/7 without downtime',
    'CTF':          'Capture The Flag — cybersecurity competitions where you legally solve hacking challenges',
    'UI':           'User Interface — the visual part of a product: buttons, forms, icons, menus',
    'UX':           'User Experience — how easy and pleasant a product is to use',
    'GDD':          'Game Design Document — full description of game mechanics, balance and levels',
    'FPS':          'Frames Per Second — 60 FPS = smooth, 15 FPS = laggy',
    'IaC':          'Infrastructure as Code — servers and networks defined in code files, not set up manually',
    'SLO':          'Service Level Objective — reliability target, e.g. 99.9% uptime',
    'ETL':          'Extract, Transform, Load — pipeline: pull data from source, process it, store it',
    'ML':           'Machine Learning — algorithms that learn patterns from data automatically',
    'AI':           'Artificial Intelligence — machines simulating human intelligence',
    'GSAP':         'GreenSock Animation Platform — powerful JavaScript library for smooth animations',
    'SIEM':         'Security Information and Event Management — security threat monitoring system',
    'OWASP':        'Open Web Application Security Project — publishes top web app vulnerabilities',
    'MVP':          'Minimum Viable Product — simplest working version to test an idea',
    'KPI':          'Key Performance Indicator — metric for tracking success (e.g. number of purchases)',
    'ORM':          'Object-Relational Mapping — library letting you work with a DB without writing SQL',
    'Agile':        'Flexible development methodology using short iterations (sprints)',
    'Scrum':        'Agile framework: 2-week sprints, daily standups, retrospectives at sprint end',
    'TypeScript':   'JavaScript with strict types — makes code more reliable and easier to maintain',
    'Redux':        'State management library for React — stores all app data in one central place',
    'Backlog':      'Prioritized list of all product tasks not yet completed',
    'DevOps':       'Culture and practices uniting development and operations for fast, reliable deployment',
    'Docker':       'Tool for running apps in isolated containers — works the same everywhere',
    'Kubernetes':   'System for managing many Docker containers at scale',
    'A/B test':     'Show two different versions to two user groups and compare which performs better',
    'Pixel-perfect':'Implementing a design exactly as the designer created it — every pixel in place',
    'Pentest':      'Penetration Test — legally hacking a system to find vulnerabilities before real hackers',
    'Standup':      'Daily 15-min team meeting: what I did, what I\'ll do, what\'s blocking me',
    'Sprint':       'Time-boxed iteration in Scrum — usually 1–2 weeks, ending with a working version',
    'Figma':        'Vector design tool for UI mockups and prototypes — the industry standard for design teams',
    'Unity':        '2D/3D game engine used in Hollow Knight, Cuphead, Pokémon GO — widely used by indie studios',
    'Godot':        'Free open-source game engine — great alternative to Unity for beginners',
    'Jira':         'Issue tracking tool — teams use it to manage bugs, tasks, and sprint boards',
    'Grafana':      'Monitoring and dashboard tool — shows real-time server metrics and graphs',
    'GitHub Actions':'Built-in CI/CD in GitHub — automatically runs tests and deploys code on each push',
    'Discord':      'Chat platform popular with gamers and developers — supports voice channels and bots',
    'Telegram':     'Messaging app with a powerful Bot API — great for automation and notifications',
    'Codeforces':   'Competitive programming platform with algorithm and data structure challenges',
    'LeetCode':     'Coding challenge platform for interview prep — focuses on algorithms and data structures',
    'Leetcode':     'Coding challenge platform for interview prep — focuses on algorithms and data structures',
    'Roblox Studio':'Built-in editor for creating games inside Roblox — monetizable with a huge audience',
    'Python':       'Programming language #1 for Data Science, ML and automation — very beginner-friendly syntax',
    'JavaScript':   'The language of the browser — makes websites interactive; also runs on servers via Node.js',
    'React':        'JavaScript UI library by Meta — the most popular frontend framework',
    'Git':          'Version control system — records code history and enables team collaboration',
    'Linux':        'Open-source OS — powers most servers and is the foundation of DevOps tooling',
    'Canva':        'Online design editor for non-designers — templates for posts, presentations, logos',
    'Vue':          'JavaScript framework for building UIs — popular alternative to React, widely used in Europe and Asia',
    'Zustand':      'Tiny, simple state management for React — a Redux alternative without the boilerplate',
    'Pinia':        'Official state management library for Vue 3 — the modern replacement for Vuex',
    'Next.js':      'Framework on top of React — adds SSR, routing, image optimization. Pages load faster.',
    'Node.js':      'JavaScript on the server — lets you write backend in the same language as frontend',
    'Express':      'Minimal web framework for Node.js — the foundation of most JS backends',
    'Prisma':       'Modern ORM for Node.js — clean syntax, works with PostgreSQL, MySQL, SQLite',
    'Flutter':      'Google framework for mobile and web — one codebase deploys to iOS and Android',
    'React Native': 'Meta framework — write React code, get native iOS and Android apps',
    'Expo':         'Platform on top of React Native — removes setup complexity, run with one command',
    'Flexbox':      'CSS layout model — makes it easy to align elements in rows or columns',
    'Next':         'Framework on top of React — adds server-side rendering, routing and optimization',
    'AWS':          'Amazon Web Services — the largest cloud provider: servers, storage, databases',
    'Azure':        'Microsoft cloud platform — widely used in enterprise and corporate environments',
    'GCP':          'Google Cloud Platform — cloud services including Compute Engine, BigQuery, AI tools',
    'Terraform':    'IaC tool by HashiCorp — describe your infrastructure as code, Terraform creates it',
    'Ansible':      'Server automation tool — configure dozens of machines with a single YAML file',
    'Postman':      'API testing tool — send requests and inspect responses without writing code',
    'PostgreSQL':   'Powerful open-source relational database — the standard for server-side applications',
    'MongoDB':      'NoSQL database — stores data as JSON documents instead of tables',
    'Redis':        'Ultra-fast in-memory database — used for caching and task queues',
    'TryHackMe':    'Cybersecurity learning platform — challenges run in the browser, nothing to install',
    'picoCTF':      'Beginner CTF competitions from Carnegie Mellon University — free',
    'Metasploit':   'Penetration testing framework — a toolkit of ready-made exploits for security testing',
    'Burp Suite':   'Web traffic analyzer for finding vulnerabilities — standard tool for web pentesters',
    'Wireshark':    'Network traffic analyzer — lets you see all data packets flowing through a network',
    'Kaggle':       'Data Science competition platform — datasets, notebooks, and challenges from real companies',
    'pandas':       'Python library for working with tables and data — the foundation of Data Science',
    'NumPy':        'Python library for math and matrices — the foundation most ML libraries build on',
    'TensorFlow':   'Machine learning framework by Google — used to build neural networks',
    'PyTorch':      'ML framework by Meta — preferred by researchers and in academic settings',
    'GitHub':       'Platform for hosting code and collaborative development built on Git',
    'bug bounty':   'Reward program for finding vulnerabilities — companies pay ethical hackers for findings',
    'GraphQL':      'Alternative to REST for APIs — the client specifies exactly what data it needs',
    'WebSocket':    'Protocol for real-time two-way connections — used in chats, games, trading platforms',
    'PWA':          'Progressive Web App — a website that works like a native app: offline, home screen icon',
    'SSR':          'Server-Side Rendering — page is generated on the server, loads faster and better for SEO',
    'Kanban':       'Task visualization method: columns like To Do / In Progress / Done — like Trello',
    'Wireframe':    'UI skeleton — a schematic layout without colors or fonts, just structure',
    // ── Design ──
    'Rive':         'Interactive animation tool for web and mobile — more powerful than Lottie',
    'Lottie':       'Lightweight animation format for apps — exported from After Effects, smaller than video',
    'Framer':       'Interactive prototyping tool with code — sits between Figma and real development',
    'After Effects':'Adobe tool for animations, visual effects, and motion design',
    'Miro':         'Online whiteboard for team collaboration: user journeys, flows, brainstorming',
    'FigJam':       'Figma\'s built-in whiteboard for workshops, flows, and collaborative planning',
    'Maze':         'UX testing platform — send prototypes to users and get behavioral analytics',
    // ── Gamedev ──
    'Unreal Engine':'Game engine by Epic Games — powers Fortnite, God of War, Hogwarts Legacy',
    'Blueprint':    'Visual scripting language inside Unreal Engine — build logic without writing code',
    'Lumen':        'Unreal Engine 5 global illumination system — realistic real-time shadows and reflections',
    'Nanite':       'Unreal Engine 5 geometry technology — renders billions of polygons without losing FPS',
    'C#':           'Programming language by Microsoft — used in Unity, similar to Java',
    'C++':          'Powerful programming language — used in Unreal Engine, system software, and games',
    'AAA':          'Triple-A — big-budget games with large teams: GTA, Cyberpunk, FIFA',
    'SOTA':         'State Of The Art — the best current result on a given benchmark or task',
    'itch.io':      'Platform for indie games — publish for free, accept donations, run game jams',
    'GameMaker':    '2D game engine — Undertale, Hotline Miami, and Spelunky were made with it',
    'Asset Store':  'Unity\'s marketplace — buy or download models, animations, sounds, and scripts',
    'GDC':          'Game Developers Conference — the largest dev conference; many talks are free online',
    // ── Data / ML ──
    'Tableau':      'Data visualization tool — build interactive dashboards without programming',
    'Power BI':     'Microsoft\'s BI tool for data analysis and dashboards — popular in enterprise',
    'Looker':       'Google\'s BI platform — business analytics and dashboards built on SQL models',
    'Spark':        'Apache Spark — framework for processing massive datasets in a distributed environment',
    'Airflow':      'Apache Airflow — scheduler for ETL jobs and data pipeline orchestration',
    'Kafka':        'Apache Kafka — real-time data streaming platform',
    'MLOps':        'ML Operations — practices for automating ML model training, deployment, and monitoring',
    'sklearn':      'Scikit-learn — Python ML library with ready-made algorithms: trees, SVM, clustering',
    'Jupyter':      'Jupyter Notebook — interactive environment for Data Science: code, charts, and text together',
    'RL':           'Reinforcement Learning — training via rewards and penalties; used in game AI and robotics',
    'NLP':          'Natural Language Processing — translation, chatbots, summarization, sentiment analysis',
    'LLM':          'Large Language Model — GPT-4, Claude, Gemini and similar models',
    'CUDA':         'NVIDIA\'s parallel computing platform — accelerates neural network training on GPUs',
    'Hugging Face': 'Platform with thousands of open ML models — transformers, LLMs, diffusion models',
    'dbt':          'Data Build Tool — transform data in your warehouse using SQL and Python',
    'arxiv':        'Repository of scientific papers — nearly all AI research is published here for free',
    'MLflow':       'Platform for tracking ML experiments — logs metrics, parameters, and model versions',
    'Data Warehouse':'Centralized structured data store optimized for analytics and reporting',
};


// ─── GLOSSARY additions (DevOps / QA / PM terms) ───────────────────────────
Object.assign(GLOSSARY.en, {
  'SLI': 'Service Level Indicator — a metric used to measure service quality, e.g. request success rate or response time',
  'Helm': 'Package manager for Kubernetes — simplifies deploying and configuring applications in a cluster',
  'Argo CD': 'GitOps tool — automatically deploys applications to Kubernetes from a Git repository',
  'Prometheus': 'Open-source monitoring system — collects and stores metrics from applications and infrastructure',
  'PagerDuty': 'Incident management platform — alerts on-call engineers about outages in real time',
  'Playwright': 'Browser test automation framework — supports Chrome, Firefox, and Safari out of the box',
  'Selenium': 'Popular tool for automated web application testing across different browsers',
  'pytest': 'Python testing framework — simple syntax and rich plugin ecosystem for writing and running tests',
  'JMeter': 'Load testing tool — simulates thousands of users to find performance bottlenecks',
  'k6': 'Modern load testing tool — JavaScript-based scripts with easy CI/CD integration',
  'Gatling': 'High-performance load testing tool written in Scala, great for complex test scenarios',
  'Appium': 'Automation framework for testing iOS and Android mobile applications',
  'BrowserStack': 'Cloud platform for testing on real devices and browsers without buying hardware',
  'OKR': 'Objectives and Key Results — a goal-setting framework: objective plus measurable results to track progress',
  'PRD': 'Product Requirements Document — a document describing what to build, why, and how',
  'NPS': 'Net Promoter Score — a loyalty metric measuring how likely users are to recommend the product',
  'DAU': 'Daily Active Users — the number of unique users who open the app on a given day',
  'A/B test': 'Comparing two versions of a page or feature to find which one performs better',
  'postmortem': 'Post-incident analysis — what happened, why it happened, and how to prevent recurrence',
  'ISTQB': 'International software testing qualification — a certificate validating knowledge of testing principles',
  'Platform Engineer': 'A specialist who builds internal platforms and developer tools for engineering teams',
  'Cloud Engineer': 'An engineer who designs and manages cloud infrastructure (AWS, GCP, Azure)',
  'Roadmap': 'A visual product development plan showing what will be built and when',
  'Sprint': 'A time-boxed period in Agile (usually 1–2 weeks) during which a team completes planned work',
});

// ─── GLOSSARY additions (Creative / Tools / School terms) ──────────────────
Object.assign(GLOSSARY.en, {
  'CMYK': 'Cyan Magenta Yellow Key — color model for printing. Different from RGB: printers and screens reproduce color differently',
  'RGB': 'Red Green Blue — color model for screens. All colors are created by mixing three light channels',
  'Vector': 'Image described with math (Bezier curves) — scales without losing quality. Formats: SVG, AI, EPS',
  'Raster': 'Pixel-based image — loses quality when enlarged. Formats: JPG, PNG, PSD',
  'RAW': 'Unprocessed camera file — contains maximum data, requires editing in Lightroom or Capture One',
  'Moodboard': 'A collage of references: photos, colors, textures, fonts. Shows the style direction before work begins',
  'Brand Guidelines': 'Document with rules for using visual identity: logo, colors, fonts, spacing',
  'Kerning': 'Spacing between individual letters — important for readability and typographic aesthetics',
  'Dieline': 'Flat packaging template with cut and fold lines. Used for printing and assembling boxes',
  'AIDA': 'Attention Interest Desire Action — classic copywriting formula: grab attention, spark interest, build desire, prompt action',
  'CTA': 'Call To Action — a button, headline, or phrase that tells users what to do next',
  'SEO copy': 'Text optimized for search queries — contains keywords and structure to rank in Google',
  'Reach': 'The number of unique people who saw a post. Different from views/impressions',
  'Engagement Rate': 'Percentage of your audience that interacts with content: likes, comments, shares',
  'Content plan': 'Editorial calendar: topics, formats, dates — helps run social media systematically',
  'Reels': 'Short vertical videos on Instagram — the algorithm promotes them organically better than other formats',
  'Hook': 'The first 3 seconds of a video or opening line of text that grabs attention and keeps people watching',
  'Turnaround': 'Character rotation sheet — front, side, and back views for animators and 3D modelers',
  'ArtStation': 'Professional portfolio platform for artists, illustrators, and concept artists',
  'Storyboard': 'A series of drawings showing scene sequence before shooting or animating',
  'Bokeh': 'Blurred background in a photo. Achieved with a wide aperture (low f-number)',
  'ISO': 'Camera sensor sensitivity to light. High ISO = more noise, low ISO = cleaner image',
  'Exposure': 'Amount of light hitting the sensor — depends on shutter speed, aperture, and ISO',
  'Retouching': 'Photo editing: removing blemishes, smoothing skin, color correction in Photoshop',
  'Color Grading': 'Artistic color processing: creating mood through warm/cool tones',
  'Photoshop': 'Adobe Photoshop — raster editor for photo retouching, compositing, and digital painting. Industry standard',
  'Illustrator': 'Adobe Illustrator — vector editor for logos, illustrations, and typography',
  'Lightroom': 'Adobe Lightroom — photo editing and organizing app. Non-destructive RAW processing',
  'Procreate': 'Drawing app for iPad — the most popular tool among digital illustrators',
  'Notion': 'All-in-one tool for notes, wikis, and project management. Replaces docs, spreadsheets, and Jira',
  'Clip Studio': 'Clip Studio Paint — professional app for comics, manga, and concept art',
  'Clip Studio Paint': 'Clip Studio Paint — professional illustration app for comics, manga, and concept art. Popular among digital artists',
  'Adobe XD': 'Adobe XD — UI/UX design and prototyping tool from Adobe. Used for website and app mockups',
  'InDesign': 'Adobe InDesign — layout software for multi-page publications: books, magazines, brochures',
  'Capture One': 'Professional color grading and RAW processing software. Alternative to Lightroom',
  'TikTok': 'Short-form vertical video platform — the algorithm can make content go viral from zero',
  'Instagram': 'Meta visual social network — primary platform for photographers, designers, and brands',
  'Behance': 'Adobe portfolio platform — the standard for showcasing design and illustration work',
  'Pinterest': 'Visual search and moodboard platform — a go-to inspiration source for designers',
  'Premiere': 'Adobe Premiere Pro — professional video editor for films and content creation',
  'Landing page': 'A single-page website with one goal — for example, to get you to buy something or sign up. Often used in ads',
  'Deploy': 'Publishing finished code — uploading your app or website to a server so real users can access it',
  'Framework': 'A ready-made skeleton for building a program — tools and rules so you don\'t start from scratch. Examples: React, Django',
  'Pipeline': 'A sequence of steps that run automatically one after another. For example: get data → process it → save it',
  'Backend': 'The invisible part of an app that runs on a server. It stores your password, processes purchases, sends notifications',
  'Frontend': 'Everything a user sees on screen — buttons, pages, animations. A frontend developer builds the interface',
  'Fullstack': 'A developer who can do both frontend and backend. They can build an entire product solo',
  'Microservices': 'An architecture where a large app is split into independent parts. Like LEGO: each piece works on its own',
  'Monolith': 'An application written as one large program — simpler to start, harder to scale',
  'Code review': 'When another developer checks your code before it goes live. Helps catch mistakes and improve quality',
  'Refactoring': 'Rewriting working code to make it cleaner — without changing what the program actually does',
  'Bug report': 'A detailed description of a bug: what the user did, what should have happened, and what went wrong',
  'Test case': 'A scenario for checking a program: if I press this button with this data, then this should happen. QA engineers write hundreds of them',
  'Targeting': 'Showing ads only to the right people — for example, only teenagers in Moscow who like games',
  'Content creator': 'A person who makes posts, videos, or stories for social media — for themselves or for a brand',
  'Community manager': 'A person who keeps a community alive around a brand — replies to comments and organizes activities',
  'Postmortem': 'A review after a failure: what went wrong, why, and how to prevent it from happening again',
  'CapCut': 'A free video editing app for smartphones — popular among TikTok and Instagram content creators',
  'DaVinci Resolve': 'A professional free video editing and color grading program — used in Hollywood productions',
  'Cinema 4D': 'Software for 3D animations and visual effects — popular among motion designers',
  'Blender': 'A free program for 3D modeling, animation, and rendering — used in game dev, film, and design',
  'Krita': 'A free digital painting program — a great alternative to Procreate for those without an iPad',
  'Amplitude': 'A product analytics tool — shows how users behave inside an app: what they click, where they drop off',
  'Load testing': 'Testing how many users a server can handle at once. A program simulates thousands of people simultaneously',
  'Responsive design': 'A website that looks correct on both big screens and phones — the code adjusts to any screen size',
  'FastAPI': 'A popular Python framework for building APIs — fast and beginner-friendly. A great first backend project',
  'Spring Boot': 'The main Java backend framework — used in banks, marketplaces, and large corporations',
  'Freelance': 'Working for yourself without a permanent employer — you take projects from different clients and choose your own tasks',
  'Briefing': 'A meeting or document at the start of a project — the client explains what is needed, the designer asks questions',
  'Prototype': 'A model of a future product — not a real program yet, but you can already click buttons and test the idea',
  'Brand book': 'A document with a company\'s visual style rules: which colors, fonts, and logo to use',
  'Video editing': 'Assembling a video from separate clips — cutting out unnecessary parts, adding music and effects',
  'Concept art': 'Drawings that show what a character, location, or object will look like — made before the final version',
  'Brand identity': 'A company\'s unified visual image — logo, colors, fonts — so everything looks recognizable',
  'Dribbble': 'A portfolio social network for designers — people share their work and find clients here',
  'VSCO': 'A smartphone photo editing app with beautiful presets (filters)',
  'Hootsuite': 'A service for scheduling posts across multiple social networks — write a post once, it goes out everywhere',
  'SMM': 'Social Media Marketing — promoting brands and projects through social media: Instagram, TikTok, etc.',
  'Layout': 'Arranging text and images on a page — how a book, magazine, or website looks',
  'Frame': 'A single image in a video or photo — a film is made of frames, like a word is made of letters',
  'Aperture': 'The opening in a camera lens that controls how much light enters. Affects background blur (bokeh)',
  'Composition': 'How objects are arranged in a photo or drawing. Good composition makes an image pleasant to look at',
  'Sketch': 'A quick rough drawing on paper or in an app — a draft of an idea before the final version',
  'Neural network': 'A program that can learn from data — it generates images, text, and music. Examples: ChatGPT, Midjourney',
  'Deadline': 'The final due date for a project. If the deadline is Friday — the client receives the result on Friday',
  'Technical spec': 'A document with an exact description of what needs to be done — sizes, colors, functions. Often called a brief or spec',
  'Portfolio': 'A collection of your best work — you show it to clients or employers so they can see your skill level',
  'Character design': 'Developing the appearance of a character — body shape, clothing, facial expressions. Done for games, cartoons, books',
  'Design system': 'A library of ready-made interface elements (buttons, cards, icons) — the team uses them throughout the whole product',
  'Adobe Premiere': 'Adobe Premiere Pro — professional video editor for cutting films, ads, and content',
  'Premiere Pro': 'Adobe Premiere Pro — professional video editor for cutting films, ads, and content',
  'Hemingway': 'Hemingway App — a writing tool that highlights complex sentences, unnecessary words, and shows readability level',
  'Grammarly': 'A service for checking English grammar and style — underlines mistakes and suggests fixes',
  'Later': 'A service for scheduling posts to Instagram, TikTok, and other social networks — set the time, posts go out automatically',
  'Buffer': 'A tool for scheduling social media posts — plan all your content a week in advance',
  'Google Docs': 'Free online document editor by Google — like Word, but in a browser. Great for collaboration',
  'Analytics': 'Collecting and analyzing data about user behavior — how many views, where they came from, what they clicked',
  'Text editor': 'A program for writing and editing text — from a simple notepad to Word or Google Docs',
  'text editors': 'Programs for writing and editing text — from a simple notepad to Google Docs or Word',
  'analytics': 'Collecting and studying data about user behavior — how many views, likes, clicks, and where they came from',
});

// ─── GLOSSARY additions (Motion / Video / 3D terms) ─────────────────────────
Object.assign(GLOSSARY.en, {
  'After Effects': 'Adobe After Effects — the main program for motion design and visual effects. Used for animating graphics, logos, and VFX',
  'Motion design': 'Design in motion — animated graphics, logos, and titles. Lives at the intersection of design and animation',
  'VFX': 'Visual Effects — special effects in film and video: explosions, teleportation, fantasy scenes that don\'t exist in reality',
  'Keyframe': 'A key frame in animation — you mark the start and end position of an object, the program builds the movement between them',
  'Render': 'The final calculation of a 3D scene or effects into a finished image or video. Can take seconds to hours',
  'Compositing': 'Combining different video layers into one scene — merging live footage with 3D, effects, and backgrounds',
  'Motion tracking': 'Tracking the movement of an object in video to attach graphics or an effect to it',
  'Chroma key': 'Shooting on a green screen background which is then replaced with another image or video',
  'Rotoscoping': 'Cutting out an object from video frame by frame. Used to be done by hand, now AI helps',
  'Rigging': 'Creating a skeleton for a 3D character or 2D puppet so it can be animated — like bones in a body',
  'Animation': 'Creating the illusion of movement through a series of images. Comes in 2D, 3D, stop-motion, and computer forms',
  'Nuke': 'Foundry Nuke — professional VFX and compositing tool. Used in Hollywood and major studios',
  'Houdini': 'SideFX Houdini — program for complex VFX: fire, water, and destruction simulations. Industry standard in film',
  'Maya': 'Autodesk Maya — professional program for 3D character animation. Used at Disney, Pixar, and in games',
  'Lottie': 'Animation format for web and mobile apps — exported from After Effects and very lightweight',
  'Easing': 'Smooth deceleration or acceleration at the start and end of movement. Makes animation feel natural, like the real world',
  'Timing': 'The speed and rhythm of animation. Fast movement = energy, slow = smoothness. The foundation of lifelike animation',
  'Preset': 'A ready-made effect or animation setting. Saves time — instead of manual setup, one click',
  'Codec': 'Algorithm for video compression. H.264 and H.265 for web and social media, ProRes and DNxHD for professional editing',
  'Frame rate': 'FPS — frames per second. 24fps = cinema, 30fps = TV, 60fps = games and smooth video',
  'Alpha channel': 'The transparency channel in an image or video. Needed to overlay graphics without a background',
  'Demo reel': 'A short portfolio video (30–90 sec) of your best work. The main tool for finding work in video production',
  'Particle': 'A particle in a simulation system: smoke, fire, snow, confetti. Control thousands of objects at once',
  'DaVinci Fusion': 'VFX and compositing module inside DaVinci Resolve — a powerful node-based system for visual effects',
});

// ─── GLOSSARY additions (Business / Management terms) ───────────────────────
Object.assign(GLOSSARY.en, {
  'CRM': 'Customer Relationship Management — a system for managing client relationships. Salesforce, HubSpot, and Pipedrive store all deals, contacts, and communication history',
  'KPI': 'Key Performance Indicator — a specific metric used to measure performance: sales volume, conversion rate, customer acquisition cost',
  'ROI': 'Return on Investment — how much money each invested unit generates. Formula: (profit − cost) / cost × 100%',
  'B2B': 'Business-to-Business — sales and marketing targeting other businesses rather than end consumers',
  'B2C': 'Business-to-Consumer — selling directly to the end user. Online stores, apps, and retail are classic B2C',
  'Sales funnel': 'The journey a customer takes from awareness to purchase. Wide at the top (many leads), narrow at the bottom (actual sales)',
  'Conversion rate': 'The percentage of users who complete a target action: purchase, sign-up, or subscription. A core marketing metric',
  'MVP': 'Minimum Viable Product — the simplest version of a product with one key feature, used to test a hypothesis',
  'Pitch': 'A short presentation of an idea or business to an investor or client. An elevator pitch fits in 1–2 minutes',
  'Due diligence': 'A deep investigation of a company before a deal or investment: financials, legal, risks',
  'Job offer': 'A formal proposal to a candidate: position, salary, and conditions. HR sends an offer after the final interview',
  'Onboarding': 'The process of integrating a new employee: meeting the team, training, and getting up to speed',
  'Targeting': 'Configuring ads for a specific audience by age, interests, location, and behavior',
  'P&L': 'Profit and Loss Statement — a report showing revenues, expenses, and net profit for a period',
  'DCF': 'Discounted Cash Flow — a method for valuing a company by forecasting future cash flows. The foundation of financial modeling',
  'Equity': 'Ownership stake in a company or startup. Startups often offer equity instead of or alongside salary',
  'Lead scoring': 'A system for ranking candidates or leads by set criteria to prioritize efforts',
  'Lead': 'A potential customer who has shown interest in a product. Cold lead = no prior contact; warm lead = already engaged',
  'EBITDA': 'Earnings Before Interest, Taxes, Depreciation and Amortization — a metric of operational profitability',
  'Churn': 'Churn rate — the percentage of customers or employees who leave over a given period. Lower is better',
});

// ─── GLOSSARY additions (School / Career terms for PO quiz) ─────────────────
Object.assign(GLOSSARY.en, {
  'Algorithm': 'A step-by-step set of instructions for solving a problem. Programmers write algorithms for computers — but a recipe is an algorithm too',
  'Freelance': 'Working independently without a permanent employer. You choose your own clients, projects and schedule. Common for designers, developers and writers',
  'Portfolio': 'A collection of your best work to show employers or clients. Designers show mockups, developers show GitHub projects, photographers show photos',
  'Internship': 'A temporary work placement at a company to gain real experience. Often paid, sometimes leads to a permanent job. The best way to break into a field',
  'Hackathon': 'A competition where teams build a working prototype in 24–48 hours. Great way to meet professionals and get your first hands-on experience',
  'Networking': 'Building professional relationships. Knowing the right people means colleagues who recommend you, share knowledge, and open doors to opportunities',
  'Mentor': 'An experienced specialist who helps a newcomer: answers questions, reviews mistakes, and advises on career growth. Having a mentor is a huge accelerator',
  'Startup': 'A young company with an ambitious idea and potential for rapid growth. Unlike regular businesses, startups embrace risk and aim to scale fast. Examples: Airbnb, Telegram early on',
  'Cybersecurity': 'Protecting computer systems, data and networks from hacking and breaches. Includes securing websites, investigating attacks and training users',
  'Data Analyst': 'A specialist who collects, processes and interprets data. Helps businesses make decisions based on numbers rather than gut feeling',
  'Illustrator': 'An artist who creates images for books, games, advertising and media. Works with digital tools: Procreate, Adobe Illustrator, Krita',
  'Animator': 'Creates the illusion of movement: cartoons, special effects, animated logos. Types include 2D, 3D and stop-motion animation',
  'Videographer': 'A specialist in shooting and editing video. Films ads, YouTube content, news reports. Tools: camera, Premiere Pro, DaVinci Resolve',
  'Marketer': 'A specialist who promotes products and services. Creates ad campaigns, manages social media, analyzes audiences and measures results',
  'Entrepreneur': 'A person who creates a business, takes risks and builds a team. You don\'t need millions to start — a small project counts too',
  'NGO': 'Non-Governmental Organization — works for public benefit, not profit. Charities, volunteer groups, human rights organizations — these are all NGOs',
  'Pedagogy': 'The science of education and teaching. Teachers, coaches, mentors and curriculum designers all apply pedagogy to help people learn more effectively',
  'Robotics': 'Designing and programming robots. Combines mechanics, electronics and code. Used in manufacturing, medicine, space and even household devices',
  'Biotechnology': 'Applying biological systems to create products: vaccines, medicines, genetically modified crops, biodegradable materials',
  'Prototype': 'The first working model of a product or interface. Lets you test an idea before spending time and money on full development',
  'Sketch': 'A quick rough drawing or draft of an idea. Designers and illustrators use sketches to test concepts fast before adding detail',
  'Design Thinking': 'A problem-solving method built on deeply understanding people\'s needs. 5 stages: empathize → define → ideate → prototype → test',
});

// ─── GLOSSARY additions (Career, IT-basic, AI, NGO) ───────────────────────────────────────
Object.assign(GLOSSARY.en, {
  'Soft skills': 'Personal qualities that are hard to measure: communication, empathy, time management, flexibility. Employers value them as much as technical knowledge',
  'Hard skills': 'Specific technical abilities: knowing Python, using Photoshop, bookkeeping. Easily measured and verified with certificates or tests',
  'Cover letter': 'A brief letter alongside your CV explaining why you want this specific job and what value you bring to the company',
  'ATS': 'Applicant Tracking System — software companies use to automatically filter resumes. Using keywords from the job posting in your CV helps you pass ATS screening',
  'Probation period': 'A trial phase at the start of employment (usually 1–3 months) where employer and employee evaluate each other. A permanent contract follows if both are satisfied',
  'Grade': 'A career level in a company: junior → middle → senior → lead. Determines your salary range and the scope of your responsibilities',
  'CV': 'Curriculum Vitae — a document listing your experience, education and skills. Sent to employers when applying for jobs. Should be concise and specific',
  'Hosting': 'A service that stores your website or app on a server accessible on the internet. Like renting space for your project online — Vercel, Netlify, AWS, VPS',
  'Domain': 'A website\'s address on the internet (e.g. google.com). Purchased from registrars; it tells browsers where to find your site',
  'Cache': 'Temporary data storage to speed things up. A browser saves a site\'s images in cache to avoid re-downloading them on the next visit',
  'Bug': 'An error in program code that causes an application to behave unexpectedly. Finding and fixing bugs is called debugging',
  'Debugging': 'The process of finding and fixing errors (bugs) in code. A key developer skill — being able to read error messages and trace their root cause',
  'Parsing': 'Automated extraction of data from websites or text. For example, collecting prices from an online store or contacts from a directory',
  'VPN': 'Virtual Private Network — technology that encrypts your internet connection, hides your IP address and lets you bypass geographic restrictions',
  'Cloud': 'Remote servers on the internet for storing files and running programs. Google Drive, Dropbox, AWS — all examples of cloud services',
  'Prompt': 'A text instruction you give to an AI. The more precise and detailed your prompt, the better the result',
  'Generative AI': 'A type of artificial intelligence that creates new content: text, images, music, code. Examples: ChatGPT, Midjourney, Gemini, Claude',
  'AI Hallucination': 'When AI confidently outputs false information — inventing facts, quotes, or links. Always verify important AI claims in other sources',
  'Fine-tuning': 'Further training of a pre-built neural network on specific data so it performs better on a narrow task',
  'RAG': 'Retrieval-Augmented Generation — a method where AI first searches a knowledge base for relevant documents, then generates an answer based on them. Reduces hallucinations',
  'Embeddings': 'Numerical vectors representing words, sentences or images. They allow AI to "understand" meaning and find similar objects',
  'Chatbot': 'A program for automated chat responses. Can be simple (script-based) or smart (AI-powered). Used in support, sales, and education',
  'Volunteering': 'Freely giving your time and energy to help people, organizations or nature. Volunteers work at events, hospitals, nature reserves, and shelters',
  'Grant': 'Targeted non-repayable funding for a project from a foundation, government or company. Unlike a loan, you don\'t repay it — but you must report how it was spent',
  'Fundraising': 'The systematic collection of donations and financing for non-profit projects. Includes working with donors, grant applications and crowdfunding',
  'Crowdfunding': 'Collecting financing from a large number of people via platforms (Kickstarter, Indiegogo). Lets you realize a project without traditional investors',
  'Charity': 'Voluntary help for those in need: money, goods, time or expertise. Can be personal (from individuals) or corporate',
  'Advocacy': 'Working to protect the rights and promote the interests of a specific group of people at the policy and societal level. Characteristic of human rights NGOs',
});

// ─── GLOSSARY additions (Proforientation test terms) ─────────────────────────
Object.assign(GLOSSARY.en, {
  'Career Orientation': 'The process of choosing a future profession based on interests, abilities and the job market. Career tests and counseling are tools for orientation',
  'SMM Specialist': 'Social Media Marketing specialist — promotes brands on social networks: creates content, runs ads, analyzes audiences. One of the most in-demand marketing skills',
  'Targeting Specialist': 'A specialist who configures targeted ads shown to a specific audience (by age, interests, behavior). Works with Meta, TikTok, Google Ads',
  'Copywriter': 'An author of advertising and marketing texts: slogans, product descriptions, social posts, email campaigns. Not to be confused with copyright',
  'Art Director': 'Oversees the visual style of a project or brand. Manages a team of designers, photographers and illustrators. Requires design experience and business understanding',
  'Bioinformatician': 'A specialist at the intersection of biology, informatics and mathematics. Analyzes genomic data and develops algorithms for drug discovery and DNA decoding',
  'Epidemiologist': 'A scientist who studies the spread of diseases in society: how they originate, who is at risk, and how to stop outbreaks. Became widely known during pandemics',
  'Arduino': 'A platform for creating electronic devices: a small board with a processor programmed in C++. Used for robots, smart home devices and sensors. Ideal for getting started in electronics',
  '3D Printing': 'Additive manufacturing — creating physical objects from plastic, metal or other materials based on a digital 3D model. Used in medicine, aviation, architecture and creative work',
  'Career Counselor': 'A specialist who helps people choose a profession, find a job or change careers. Analyzes strengths, builds a plan, prepares for interviews',
  'Speech Therapist': 'A specialist in correcting speech and voice. Helps children and adults with stuttering, pronunciation problems and speech development delays',
});

// ─── GLOSSARY additions (Entrepreneur L2 terms) ─────────────────────────────
Object.assign(GLOSSARY.en, {
  'Unicorn': 'A startup valued at over $1 billion. The name highlights the rarity: only about 0.1% of startups reach this level. Examples: Airbnb, Telegram, Revolut',
  'Exit': 'The moment a founder or investor sells their stake in a startup. Options: strategic acquisition (M&A), IPO, or buyout by other investors',
  'IPO': 'Initial Public Offering — a company\'s first listing of shares on a stock exchange. Allows raising large capital and lets anyone buy shares. Examples: Airbnb, Spotify IPOs',
  'Accelerator': 'An intensive startup development program: mentorship, investment, and networking over 3–6 months. Most famous: Y Combinator (USA), Techstars, Station F (France)',
  'CAC': 'Customer Acquisition Cost — the cost of acquiring one new customer. Calculated as: total marketing spend ÷ number of new customers. A key unit economics metric',
  'LTV': 'Lifetime Value — total revenue generated by one customer over the entire relationship. Healthy business: LTV should be 3x or more than CAC',
  'Margin': 'The difference between selling price and cost of goods or services. A 30% margin means: for every $100 in revenue, $30 is gross profit before operating expenses',
  'Theory of Change': 'A strategic tool for social projects: describes how specific actions will lead to desired social changes. Used in NGOs and impact businesses',
  'Impact Investing': 'Investments in projects that deliver not only financial return but also measurable social or environmental benefit. A growing market of $1 trillion+',
  'Retainer': 'A payment model for agencies or consultants: a fixed monthly fee for an agreed scope of work. Provides predictable income for the service provider',
  'ICP': 'Ideal Customer Profile — a description of the perfect customer: the company or person your product fits best and who will bring the most value. The foundation of marketing and sales',
  'Monetization': 'The way a product or audience is turned into revenue. Models: subscription, advertising, transaction fees, data sales, freemium. Choosing a monetization model is a key business decision',
});


// Sales L2 glossary
Object.assign(GLOSSARY.en, {
  'Upsell': 'Selling a customer a more expensive or upgraded version of a product they already intend to buy.',
  'Cross-sell': 'Offering additional products or services alongside a main purchase.',
  'Account Manager': 'A sales professional responsible for retaining, developing and growing revenue from existing client accounts.',
  'Business Development': 'A function focused on finding strategic partnerships, new markets and growth channels for the company.',
  'Cold outreach': 'The first contact with a potential client who has no prior relationship — a cold call or cold email.',
  'Decision Maker': 'The person in a company who has the authority to sign contracts or approve budgets. The key contact in B2B sales.',
  'SPIN Selling': 'A sales methodology based on 4 question types: Situation, Problem, Implication, Need-Payoff. Highly effective in B2B.',
  'Net Revenue Retention': 'NRR — measures how much revenue is retained from existing customers including upsells, cross-sells, and churn. NRR > 100% means growth without new customers.'
});


// Marketing L2 glossary
Object.assign(GLOSSARY.en, {
  'Brand Manager': 'A specialist responsible for the image, positioning and perception of a brand in the market.',
  'Positioning': 'The place a product or brand occupies in consumers\' minds relative to competitors.',
  'Tone of Voice': 'The style and manner in which a brand communicates with its audience: friendly, expert, inspirational.',
  'Brand Book': 'A document defining rules for corporate identity usage: logo, colors, fonts, communication tone.',
  'Go-to-Market': 'A strategy for launching a product: target audience, channels, value proposition, and rollout plan.',
  'ROAS': 'Return on Ad Spend — revenue generated per dollar spent on advertising.',
  'Product Marketing': 'A marketing function responsible for product positioning, market launch and collaboration with sales teams.',
  'A/B Test': 'Comparing two versions (A and B) of a page, ad or email to determine which performs better.',
  'Growth Hacking': 'An approach to rapid business growth through experiments at the intersection of marketing, product and analytics.'
});

// Marketing L2 extended glossary
Object.assign(GLOSSARY.en, {
  'Influencer': 'A blogger or opinion leader with an audience that trusts their recommendations. Influencer marketing uses these people to promote products.',
  'Content Marketing': 'A strategy for attracting audiences through useful content — articles, videos, podcasts — without direct advertising.',
  'SEO': 'Search Engine Optimization — optimizing a website to rank in search engines and attract free (organic) traffic from Google.',
  'SEM': 'Search Engine Marketing — paid promotion in search engines through pay-per-click ads (Google Ads, Bing Ads).',
  'Email Marketing': 'Communicating with customers via email: newsletters, triggered messages and nurture sequences for warming up and retention.',
  'Organic Traffic': 'Website visitors from free sources — search engines, social media, direct visits. The opposite of paid traffic.',
  'Paid Traffic': 'Visitors acquired through an advertising budget: targeted ads, search ads, display banners.',
  'CRO': 'Conversion Rate Optimization — improving the percentage of visitors who complete a desired action on a site.',
  'Retention': 'Keeping users engaged with a product over time. Retention marketing uses email, push notifications and promotions for existing customers.',
  'Brand Awareness': 'The degree to which a target audience knows and recognizes a company or product.',
  'Jobs-to-be-Done': 'A framework: customers "hire" a product to accomplish a job in their life. Helps understand the true motivation behind a purchase.',
  'Sales Enablement': 'Equipping the sales team with materials, tools and data to close deals more effectively.',
  'Share of Voice': 'A brand\'s share of mentions within its category. Shows brand visibility relative to competitors.',
  'Buyer Persona': 'A detailed profile of the ideal customer: age, pain points, goals and behavior. The foundation of any marketing strategy.',
  'Value Proposition': 'A clear statement of why a customer should choose this product and what problem it solves.',
  'Product-Market Fit': 'PMF — the point at which a product precisely satisfies a market need. A sign: users recommend the product spontaneously.',
  'Performance Marketing': 'Results-based marketing where you pay for specific actions (click, lead, sale). The opposite of brand/image advertising.'
});

// HR L2 glossary
Object.assign(GLOSSARY.en, {
  'Recruiting': 'The process of finding, attracting and selecting candidates for open positions in a company.',
  'Employer Brand': 'A company\'s reputation as an employer — how current and potential employees perceive it.',
  'eNPS': 'Employee Net Promoter Score — an employee loyalty index showing how likely they are to recommend the company as a place to work.',
  'HR Business Partner': 'A strategic HR professional who works closely with a business unit and solves challenges through people.',
  'Turnover': 'The percentage of employees who left the company in a given period. High turnover signals cultural or management issues.',
  'L&D': 'Learning & Development — the function responsible for employee training and professional growth within a company.',
  'HRIS': 'Human Resource Information System — a system for managing employee data: headcount, leave, performance reviews, documents.',
  'Time-to-hire': 'The time from opening a vacancy to a candidate accepting the offer. A key recruiting efficiency metric.',
  'People Analytics': 'Data-driven HR analysis of employee data: predicting attrition, evaluating hiring effectiveness, measuring engagement.',
  'Job Offer': 'A formal employment proposal specifying the role, salary and conditions.'
});

// Analyst L2 glossary
Object.assign(GLOSSARY.en, {
  'BPMN': 'Business Process Model and Notation — a standard graphical notation for documenting business processes. Used by business analysts to map workflows.',
  'User Story': 'A short requirements description from the user\'s perspective: "As a [role] I want [action] so that [goal]." The foundation of agile development.',
  'Stakeholder': 'Any person or group affected by a project or whose interests must be considered when designing a solution.',
  'Data Warehouse': 'A centralized database where data from multiple sources is collected and stored for analytics and reporting.',
  'ETL': 'Extract, Transform, Load — the process of pulling data from sources, transforming it and loading it into a warehouse. The backbone of BI infrastructure.',
  'Dashboard': 'An interactive panel displaying key metrics and reports visually to support real-time decision-making.',
  'Cohort': 'A group of users sharing a common characteristic (e.g. registration date). Cohort analysis shows how different groups behave over time.',
  'MAU': 'Monthly Active Users — the number of unique users who interacted with the product in a month. A key growth metric.',
  'Conversion Funnel': 'The sequence of steps from a user\'s first touch to a target action. Funnel analysis reveals where users drop off.',
  'BI': 'Business Intelligence — a set of tools, processes and technologies for collecting, analyzing and visualizing data to support business decisions.',
  'Tableau': 'A popular data visualization tool for building interactive dashboards. Widely used in BI and analytics.',
  'Power BI': 'Microsoft\'s business analytics tool for connecting to data sources and creating reports and dashboards. One of the most popular BI tools.',
  'Jupyter': 'Jupyter Notebook — a web environment for writing and running Python code, analyzing data and creating visual reports with charts.',
  'Mixpanel': 'A product analytics platform for tracking events, conversion funnels and user behavior in applications.'
});

// Science & Medicine L1 glossary
Object.assign(GLOSSARY.en, {
  'Diagnosis': 'The process of identifying a disease based on symptoms, tests, and examinations. A core medical skill.',
  'Medical History': 'A patient\'s account of past and present health: complaints, symptoms, prior illnesses. Taken at first consultation.',
  'MRI': 'Magnetic Resonance Imaging — a technique that visualizes internal organs using magnetic fields, without radiation.',
  'CT Scan': 'Computed Tomography — a method that produces cross-sectional images of the body using X-rays.',
  'ECG': 'Electrocardiogram — a recording of the heart\'s electrical activity. Used to diagnose heart conditions.',
  'Surgery': 'The branch of medicine that treats diseases through operative procedures. Surgeons work in the operating room.',
  'General Practitioner': 'A primary care physician who handles most common conditions and refers patients to specialists.',
  'Pediatrician': 'A doctor specializing in treating children, monitoring development from birth to age 18.',
  'Neurology': 'The branch of medicine studying the nervous system. Neurologists treat strokes, migraines, and neurodegeneration.',
  'Oncology': 'The branch of medicine studying tumors. Oncologists diagnose and treat cancer.',
  'Hypothesis': 'An assumption a scientist tests through experimentation. Must be testable and falsifiable.',
  'Experiment': 'A controlled test to verify a hypothesis. Involves experimental and control groups.',
  'Peer Review': 'The evaluation of a scientific paper by experts in the field before journal publication.',
  'Meta-analysis': 'A statistical method combining data from multiple studies for a more precise conclusion.',
  'Clinical Trial': 'A controlled study testing a new drug or treatment in humans under a strict protocol.',
  'Placebo': 'A neutral substance with no active ingredient, used in the control group of a clinical trial.',
  'Randomization': 'Random assignment of participants to study groups to eliminate systematic bias.',
  'CBT': 'Cognitive Behavioral Therapy — a psychotherapy that changes negative thoughts and behaviors.',
  'DSM': 'Diagnostic and Statistical Manual of Mental Disorders — the standard classification for psychiatric diagnoses.',
  'Neuropsychology': 'The branch of psychology studying brain-behavior relationships. Assesses cognitive function after injuries.',
  'Cognitive Bias': 'Systematic errors in thinking that distort perception of reality. Addressing them is central to CBT.',
  'Psychotherapy': 'Treatment of mental disorders and emotional difficulties through talk-based and behavioral techniques.',
  'Neuroplasticity': 'The brain\'s ability to reorganize by forming new neural connections in response to experience and learning.',
  'Empathy': 'The ability to understand and share the feelings of another person. A key skill for psychologists and doctors.',
  'Pharmacokinetics': 'Studies how the body absorbs, distributes, metabolizes, and excretes a drug.',
  'Pharmacodynamics': 'Studies how a drug affects the body: mechanism of action, effects, and dosing.',
  'Clinical Trials': 'Controlled studies of new drugs in humans. Go through 4 phases before approval.',
  'Generic Drug': 'A copy of a brand-name drug with the same active ingredient, produced after the patent expires.',
  'Side Effects': 'Undesirable reactions to a drug that are unrelated to its primary therapeutic action.',
  'Regulatory Affairs': 'The rules and requirements drugs must meet for registration and market approval.',
  'CRISPR': 'A gene-editing technology with single-nucleotide precision. A revolution in genetic engineering.',
  'Genomics': 'The branch of molecular biology studying an organism\'s genome — its complete genetic information.',
  'Sequencing': 'Determining the nucleotide sequence of DNA or RNA. The basis of molecular diagnostics and bioinformatics.',
  'Bioinformatics': 'The use of computational and statistical methods to analyze biological data, especially genomic data.',
  'PCR': 'Polymerase Chain Reaction — a technique that amplifies DNA segments for detection and analysis.',
  'Antibody': 'An immune system protein that recognizes foreign agents. The basis of immunotherapy and diagnostic tests.',
  'Vaccine': 'A preparation that builds immunity to an infection without causing disease. The foundation of preventive medicine.',
  'mRNA': 'Messenger RNA — a molecule carrying instructions for protein synthesis. The basis of Pfizer and Moderna vaccines.',
  'Stem Cells': 'Undifferentiated cells capable of becoming different cell types. Promising for regenerative medicine.',
  'Biodiversity': 'The variety of life on Earth: species, genes, and ecosystems. An indicator of nature\'s health.',
  'Ecosystem': 'A community of living organisms and their non-living environment, interacting as a whole.',
  'Carbon Footprint': 'The total greenhouse gas emissions caused by an individual, organization, or product.',
  'GIS': 'Geographic Information System — software for collecting, storing, and analyzing spatial data.',
  'Environmental Monitoring': 'Systematic observation of the state of the natural environment: air, water, soil, and biota.',
  'Climate Model': 'A computer simulation of Earth\'s climate used to forecast changes and assess impacts.'
});

// Core IT + cross-domain glossary
Object.assign(GLOSSARY.en, {
  'API': 'Application Programming Interface — an interface that allows programs to communicate with each other.',
  'REST API': 'An architectural style for building APIs using HTTP requests. The most common web service standard.',
  'GraphQL': 'A query language for APIs developed by Facebook. Clients request exactly the data they need.',
  'SQL': 'Structured Query Language for relational databases (PostgreSQL, MySQL, SQLite).',
  'NoSQL': 'Schema-less databases: MongoDB, Redis, Cassandra. Used for flexible or highly scalable data.',
  'Python': 'A high-level programming language. Popular in Data Science, AI/ML, backend development, and automation.',
  'JavaScript': 'The primary language of web development. Runs in the browser and on the server (Node.js).',
  'TypeScript': 'A typed superset of JavaScript. Makes code more reliable and maintainable in large projects.',
  'Git': 'A version control system. Tracks code changes, enables team collaboration, and allows rollbacks.',
  'Linux': 'A family of open-source operating systems. The standard for servers, DevOps, and cloud infrastructure.',
  'DevOps': 'A culture and practice uniting development (Dev) and operations (Ops) for fast, reliable software delivery.',
  'CI/CD': 'Continuous Integration / Continuous Delivery — automating build, test, and deployment on every commit.',
  'Docker': 'A containerization platform that packages an application with all its dependencies into an isolated container.',
  'Kubernetes': 'A container orchestration system. Manages deployment, scaling, and reliability of Docker containers.',
  'Terraform': 'An Infrastructure as Code tool: defines cloud infrastructure in configuration files.',
  'Ansible': 'An agentless tool for automating server configuration and application deployment.',
  'Grafana': 'A metrics and logs visualization platform. Builds dashboards for real-time system monitoring.',
  'AWS': 'Amazon Web Services — the largest cloud provider, offering 200+ services: compute, storage, AI.',
  'Azure': 'Microsoft\'s cloud platform. Widely used in enterprise and integrates deeply with Microsoft products.',
  'GCP': 'Google Cloud Platform. Strong in data analytics, BigQuery, and AI/ML tooling.',
  'Agile': 'An iterative software development methodology: short cycles, close customer collaboration, adaptability.',
  'Scrum': 'An Agile framework with fixed sprints, roles (Product Owner, Scrum Master), and ceremonies.',
  'Kanban': 'A workflow management method using a visual board with columns (To Do / In Progress / Done).',
  'UI/UX': 'UI — visual interface design. UX — the user\'s experience interacting with a product. Often work together.',
  'Figma': 'A cloud-based interface design and prototyping tool. The standard for UI/UX designers.',
  'Wireframe': 'A schematic layout of an interface — structure and element placement without visual design.',
  'SIEM': 'Security Information and Event Management — a system for collecting and analyzing security events in real time.',
  'Game Design': 'The design of game mechanics, levels, balancing, and user experience in a video game.',
  'Unity': 'A cross-platform game engine. Popular for 2D/3D games and VR/AR. Language: C#.',
  'Unreal Engine': 'A powerful game engine by Epic Games. Used for AAA games, film, and architectural visualization.',
  'C#': 'A Microsoft programming language. Used in Unity, .NET applications, and enterprise development.',
  'C++': 'A high-performance programming language. Used in real-time systems, games (Unreal Engine), and OS.',
  'Machine Learning': 'A subset of AI: algorithms that learn from data without being explicitly programmed.',
  'Deep Learning': 'A Machine Learning subset based on deep neural networks. Applied in computer vision and NLP.',
  'Data Science': 'A multidisciplinary field combining statistics, programming, and domain expertise to extract insights from data.',
  'NumPy': 'A Python library for numerical computing. The foundation of most scientific and ML libraries.',
  'TensorFlow': 'Google\'s machine learning framework. Used for training and deploying neural networks.',
  'PyTorch': 'Facebook\'s Deep Learning framework. Popular in research for its dynamic computation graph.',
  'LLM': 'Large Language Model — a large AI language model (GPT, Claude, Llama). The foundation of generative AI.',
  'Transformer': 'A neural network architecture underlying LLMs. Introduced in "Attention Is All You Need" (2017).',
  'CFO': 'Chief Financial Officer — the executive responsible for financial strategy, budgets, and reporting.',
  'Due Diligence': 'The process of verifying a company before a deal or investment: finances, legal matters, risks.',
  'Architecture': 'In IT — the high-level structure of a system: components, their interactions, and design principles.'
});
